import assert from 'node:assert/strict';
import {GET,POST} from '../app/api/grade/route';
import {env} from './worker-env';
import {challenges} from '../app/workbench-data';
const c=challenges[0];const draft={caseId:1,rows:c.outputs,memo:{recommendation:'Delay expansion',analysis:'Investigate the margin decline.',assumptions:'Verify cost ratios.',risks:'Mix may explain changes.',alternatives:'Pilot selective expansion.',execution:'Operations team audits waste in 30 days.'},visuals:[],scenario:c.data.map(d=>d.value),elapsed:120};
const critique={summary:'Test critique',verdict:'Test verdict',reasoning:{score:20,feedback:'test'},feasibility:{score:15,feedback:'test'},communication:{score:5,feedback:'test'},strengths:['test'],gaps:[{claim:'test',issue:'test',consequence:'test',fix:'test'}],alternatives:['test'],nextSteps:['test']};
let user=0;const req=(body:unknown=draft,headers:Record<string,string>={})=>new Request('http://localhost:3000/api/grade',{method:'POST',headers:{'Content-Type':'application/json','oai-authenticated-user-id':'test-'+user++,Origin:'http://localhost:3000',...headers},body:JSON.stringify(body)});
assert.equal((await (await GET()).json() as {available:boolean}).available,false);
assert.equal((await POST(new Request('http://localhost:3000/api/grade',{method:'POST'}))).status,401);
assert.equal((await POST(req(draft,{Origin:'https://evil.example'}))).status,403);
assert.equal((await POST(req())).status,503);
env.OPENAI_API_KEY='unit-test-only-not-a-key';
assert.equal((await (await GET()).json() as {available:boolean}).available,true);
assert.equal((await POST(req({...draft,rows:[]}))).status,400);
assert.equal((await POST(req({...draft,scenario:[]}))).status,400);
assert.equal((await POST(req(draft,{'content-length':'200000'}))).status,413);
let calls=0;
globalThis.fetch=async(_input,init)=>{calls++;const sent=JSON.parse(String(init?.body));assert.equal(sent.store,false);assert.equal(sent.text.format.strict,true);const content=JSON.parse(sent.input);assert.equal(content.verifiedModelReport.score,100);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(critique)}]}]})};
let result=await POST(req());assert.equal(result.status,200);let payload=await result.json() as {overall:number;modelPoints:number};assert.equal(payload.modelPoints,40);assert.equal(payload.overall,80);assert.equal(calls,1);
globalThis.fetch=async()=>Response.json({status:'incomplete',output:[]});assert.equal((await POST(req())).status,502);
globalThis.fetch=async()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'No'}]}]});assert.equal((await POST(req())).status,502);
globalThis.fetch=async()=>new Response('',{status:429});assert.equal((await POST(req())).status,502);
globalThis.fetch=async()=>{throw new DOMException('Timeout','TimeoutError')};result=await POST(req());assert.equal(result.status,502);assert.match((await result.json() as {error:string}).error,/too long/);
for(let i=0;i<4;i++)await POST(req(draft,{'oai-authenticated-user-id':'rate-test'}));assert.equal((await POST(req(draft,{'oai-authenticated-user-id':'rate-test'}))).status,429);
console.log('PASS: authenticated grading API, origin checks, bounded inputs, missing-key state, server-computed marks, structured critique, refusals, timeouts, upstream failure and request throttling. Live model grading not exercised.');
