export function SiteFooter(){return <footer className="site-footer"><span>© 2026 Casecraft. Code licensed under MIT.</span><nav aria-label="Site information"><a href="?page=terms">Terms & content use</a><a href="?page=privacy">Privacy & your work</a></nav><span>Independent of DECA, FBLA, and employers.</span></footer>}
export default function LegalPage({page}:{page:'terms'|'privacy'}){return <div className="app practice-app"><header><a className="brand" href="./">casecraft</a><a href="./">Back to practice</a></header><main className="legal-page"><span className="eyebrow">CASECRAFT / {page==='terms'?'CONTENT USE':'PRIVACY'}</span><h1>{page==='terms'?'Practice freely. Respect the work.':'Your practice, your work.'}</h1><p className="intro">Effective September 11, 2026</p>{page==='terms'?<>
<h2>Using Casecraft</h2><p>You may use Casecraft for personal learning and classroom practice, including the provided draft, review-prompt and export tools. Practice assessments are learning feedback, not official competition scores, admissions decisions or employer evaluations. Check the linked organizer’s current rules before competing.</p>
<h2>Open-source software</h2><p>Casecraft’s original software and documentation are available under the MIT license. You may use, copy, modify and redistribute that software, including commercially, while keeping the copyright and license notices. The software is provided without warranty. Third-party materials and trademarks are not relicensed by this permission.</p>
<h2>Your submissions</h2><p>Your original answers, calculations and charts remain yours. You may save, share and reuse your own work. Sharing a debrief with an adviser or teammate for feedback is allowed; third-party competition materials remain subject to their owners’ rights.</p>
<h2>Third-party material</h2><p>DECA and FBLA names, indicators, criteria and linked documents belong to their respective rights holders. Casecraft’s notice does not claim ownership of them. Official examples are linked separately; Casecraft’s original scenarios and variations are not official past papers. Third-party software remains subject to its own license.</p>
<h2>Brand and affiliation</h2><p>Do not imply that Casecraft endorses a copied service or that your product is Casecraft. Casecraft is independent of DECA, FBLA and the employers referenced in interview guidance. No trademark registration is claimed by this notice.</p>
</>:<>
<h2>Browser storage</h2><p>Bookmarks and your selected practice path are stored locally on your device. Drafts, submitted responses, practice history and saved reviews use the current browser tab’s session storage. They are not a cloud backup and do not automatically sync between devices. Closing a tab, clearing browser data or storage restrictions can remove them; export important work.</p>
<h2>Written feedback</h2><p>The competition and interview workspaces do not automatically send your written answer to an AI service. “Copy grading prompt” or “Copy review prompt” puts the case and your submitted work on your clipboard, or downloads a text file if clipboard access fails. If you paste it into ChatGPT, that service receives it under its own terms and privacy policy. Avoid including information you do not want to share there.</p>
<h2>Intro music</h2><p>The intro automatically connects to Spotify’s official player and attempts playback, subject to browser and Spotify restrictions. Spotify receives technical request information and may use cookies under its own privacy policy. Casecraft does not host recordings. Only specific recordings marked non-explicit by Spotify are selected; availability, previews and sign-in requirements are controlled by Spotify. Turning music off or entering the site stops playback. Your music-off preference is saved in this browser.</p>
<h2>Files and charts</h2><p>Draft imports are processed in your browser. Export buttons create files on your device. Anyone you choose to share those files with can read their contents, including the answers and feedback inside them.</p>
<h2>Hosting and links</h2><p>The hosting provider may process normal technical request data, such as IP addresses and browser information, to deliver and protect the website. External links open services with their own privacy practices. Casecraft’s practice workspace does not add advertising trackers or a cloud account database.</p>
<h2>Remove local practice data</h2><p>Use your browser’s site-data controls to clear Casecraft storage. Save an export first if you want to keep your work. Clearing Casecraft’s data does not remove files you downloaded or work you separately pasted into another service.</p>
</>}<p className="legal-end">Questions about a linked competition resource should be directed to its organizer. These notices describe the current practice workspace.</p></main><SiteFooter/></div>}
