'use client';
import Intro from './intro';
import Tutorial,{TutorialIntro,type GuidePath} from './training/tutorial';
import LegalPage,{SiteFooter} from './legal';
import {useEffect,useMemo,useRef,useState} from 'react';
import {CircleHelp,Bookmark,X,Layers3,ArrowUpRight,ArrowRight,Search,GraduationCap,BriefcaseBusiness,ChevronRight,ArrowLeft,Clock3,Check,MessageSquareText,PenLine,ChartNoAxesCombined} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {catalog,getCases,practiceCount,formatNote,type Event,type Path,type PracticeCase} from './training/engine';
import Practice from './training/practice';
import CompetitionPractice from './training/competition-practice';
import {profiles} from './training/competition';
const pathNames={deca:'DECA',fbla:'FBLA',interviews:'Interview Prep'};
export default function Home(){
 const[intro,setIntro]=useState(()=>{try{return !new URLSearchParams(window.location.search).has('page')&&sessionStorage.getItem('casecraft-entered-v1')!=='yes'}catch{return true}});
 function enterSite(){setIntro(false);try{sessionStorage.setItem('casecraft-entered-v1','yes')}catch{}}
 const[guide,setGuide]=useState<GuidePath|null>(null);
 const[legal,setLegal]=useState<'terms'|'privacy'|null>(null);
 useEffect(()=>{const page=new URLSearchParams(window.location.search).get('page');if(page==='terms'||page==='privacy')setLegal(page)},[]);
 const[path,setPath]=useState<Path>('deca'),[search,setSearch]=useState(''),[cluster,setCluster]=useState('all'),[format,setFormat]=useState('all'),[event,setEvent]=useState<Event|null>(null),[active,setActive]=useState<PracticeCase|null>(null),[history,setHistory]=useState<{id:string;caseId?:string;title:string;score:number;max?:number}[]>([]);
 const[favorites,setFavorites]=useState<string[]>([]),[savedOnly,setSavedOnly]=useState(false),[preferencesReady,setPreferencesReady]=useState(false),[lastCase,setLastCase]=useState<string|null>(null),[preferencesNotice,setPreferencesNotice]=useState(''),[caseSearch,setCaseSearch]=useState(''),[caseLimit,setCaseLimit]=useState(18);
 const searchInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('casecraft-preferences-v1')||'{}');if(Array.isArray(saved.favorites))setFavorites(saved.favorites.filter((id:unknown)=>typeof id==='string'&&catalog.some(e=>e.id===id)));if(['deca','fbla','interviews'].includes(saved.path))setPath(saved.path);const last=sessionStorage.getItem('casecraft-last-case');if(last)setLastCase(last)}catch{setPreferencesNotice('Browser preferences unavailable. You can still practice and export drafts.')}setPreferencesReady(true)},[]);
 useEffect(()=>{if(!preferencesReady)return;try{localStorage.setItem('casecraft-preferences-v1',JSON.stringify({favorites,path}))}catch{setPreferencesNotice('Saved events are temporary because browser storage is unavailable.')}},[favorites,path,preferencesReady]);
 useEffect(()=>{if(!active)return;setLastCase(active.id);try{sessionStorage.setItem('casecraft-last-case',active.id)}catch{}window.scrollTo({top:0,behavior:'instant'})},[active]);
 useEffect(()=>{function shortcut(e:KeyboardEvent){const target=e.target as HTMLElement;if(e.key==='/'&&!active&&!event&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!target.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(target.tagName)){e.preventDefault();searchInput.current?.focus()}}window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut)},[active,event]);
 function toggleFavorite(id:string){setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 function resume(id:string){const found=catalog.find(e=>e.id===id.split(':')[0]);if(found){const next=getCases(found).find(c=>c.id===id);if(next){setPath(found.path);setEvent(found);setActive(next)}}}
 const lastEvent=lastCase?catalog.find(e=>e.id===lastCase.split(':')[0]):null;
 const resumeCase=lastEvent?getCases(lastEvent).find(c=>c.id===lastCase):null;
 useEffect(()=>{try{const h=JSON.parse(sessionStorage.getItem('casecraft-practice-history-v3')||'[]');if(Array.isArray(h))setHistory(h.filter(x=>typeof x.id==='string'&&typeof x.title==='string'&&Number.isFinite(x.score)).slice(0,30))}catch{}},[]);
 function record(caseId:string,title:string,score:number,max=100,component=''){const id=component?`${caseId}#${component}`:caseId;setHistory(h=>{const next=[{id,caseId,title,score,max},...h.filter(x=>x.id!==id)].slice(0,30);try{sessionStorage.setItem('casecraft-practice-history-v3',JSON.stringify(next))}catch{}return next})}
 const all=catalog.filter(e=>e.path===path),visible=all.filter(e=>(!savedOnly||favorites.includes(e.id))&&(cluster==='all'||e.cluster===cluster)&&(format==='all'||e.format===format)&&search.toLowerCase().trim().split(/\s+/).every(term=>`${e.name} ${e.code} ${e.cluster} ${e.domain} ${e.format}`.toLowerCase().includes(term)));
 const clusters=[...new Set(all.map(e=>e.cluster))].sort(),formats=[...new Set(all.map(e=>e.format))].sort();
 function changePath(v:string){setPath(v as Path);setEvent(null);setSearch('');setCluster('all');setFormat('all');setSavedOnly(false)}
 const cases=useMemo(()=>event?getCases(event):[],[event]);
 useEffect(()=>{setCaseSearch('');setCaseLimit(18)},[event?.id]);
 const filteredCases=cases.filter(c=>`${c.title} ${c.prompt} ${c.task}`.toLowerCase().includes(caseSearch.toLowerCase().trim()));
 if(legal)return <LegalPage page={legal}/>;
 return <div className="app practice-app"><a className="skip-link" href="#practice-content">Skip to practice</a><header><a className="brand" href="./"><span className="brandmark"><Layers3 size={23}/></span>casecraft<span className="beta">PRACTICE</span></a><div className="header-help"><button className="guide-button" onClick={()=>setIntro(true)}>Intro & music</button><button className="guide-button" onClick={()=>setGuide(path==='interviews'?'career':'competition')}>How to practice <CircleHelp size={17}/></button></div></header><div id="practice-content" tabIndex={-1}/>{active&&event?(event.path==='interviews'?<Practice key={active.id} event={event} c={active} onBack={()=>setActive(null)} onReview={(score)=>record(active.id,active.title,score)} onNext={()=>{const next=cases[(active.index+1)%cases.length];setActive(next)}}/>:<CompetitionPractice key={active.id} event={event} c={active} onBack={()=>setActive(null)} onReview={(score,max,component)=>record(active.id,`${active.title} · ${component}`,score,max,component)} onNext={()=>setActive(cases[(active.index+1)%cases.length])}/>):<main>
 {event?<><button className="text-button back-link" onClick={()=>setEvent(null)}><ArrowLeft size={16}/> All {pathNames[path]} {path==='interviews'?'roles':'events'}</button><div className="eyebrow">{event.code||event.cluster} / {pathNames[path]}</div><div className="event-heading"><div><h1>{event.name}</h1><p className="intro">{event.format}</p></div><span className="outline-pill">{cases.length} practice options</span></div><div className="event-context"><p>{event.path==='interviews'?formatNote(event):profiles[event.id]?.note}</p><a href={event.source} target="_blank" rel="noreferrer">Official {path==='interviews'?'interview guidance':'event information'} <ArrowUpRight size={15}/></a></div><div className="section-title"><div><h2>{path==='interviews'?'Practice the answer. Then the follow-up.':'Choose your next rehearsal.'}</h2><p>{path==='interviews'?'Technical and behavioral drills, with follow-up questions.':'Rehearse your event’s role, requirements and official scoring criteria.'}</p></div></div><div className="case-library-tools"><label className="search-box"><Search size={18}/><input value={caseSearch} onChange={e=>{setCaseSearch(e.target.value);setCaseLimit(18)}} placeholder="Find a topic, constraint or skill…" aria-label="Search practice options"/></label><p>{event.path==='interviews'?'8 case families, each with a core problem and two interviewer probes.':'Original core cases and clearly labeled rehearsal variations. Variations add constraints while preserving the event’s sourced requirements.'}</p><span aria-live="polite">{filteredCases.length} matching practices</span></div><div className="event-grid case-options">{filteredCases.slice(0,caseLimit).map((c)=>{const last=history.find(h=>(h.caseId||h.id)===c.id);return <button className="event-card" key={c.id} onClick={()=>setActive(c)}><span className="case-index">{String(c.index+1).padStart(2,'0')} <span>{path==='interviews'?(c.numbers.length?'Numerical + written':'Written practice'):profiles[event!.id]?.format}</span></span><h3>{c.title}</h3><p>{c.prompt}</p><span className="card-action">{last?<><Check size={15}/> Last recorded score: {last.score}/{last.max||100}</>:<><Clock3 size={14}/> {path==='interviews'?'Self-paced · Optional challenge':profiles[event!.id]?.prepMinutes?`${profiles[event!.id].prepMinutes} min prep · ${profiles[event!.id].presentationMinutes} min present`:'Plan · Produce · Defend'}</>}<ArrowRight size={17}/></span></button>})}</div>{filteredCases.length>caseLimit&&<button className="secondary-button load-practices" onClick={()=>setCaseLimit(v=>v+18)}>Show 18 more practices <ArrowRight size={16}/></button>}{filteredCases.length===0&&<div className="empty-catalog"><h3>No matching practices</h3><button className="text-button" onClick={()=>setCaseSearch('')}>Clear search</button></div>}<Resources path={path}/></>:<>
 <TutorialIntro onStart={setGuide}/><div className="audience-switch"><button className={path!=='interviews'?'selected':''} onClick={()=>changePath('deca')}><GraduationCap size={23}/><span><b>Competition Hall</b><small>High school · DECA & FBLA</small></span><ArrowRight size={18}/></button><button className={path==='interviews'?'selected':''} onClick={()=>changePath('interviews')}><BriefcaseBusiness size={23}/><span><b>Career Launchpad</b><small>University · Graduate study · Careers</small></span><ArrowRight size={18}/></button></div><div className="eyebrow">{path==='interviews'?'CAREER LAUNCHPAD':'COMPETITION HALL'}</div><div className="heading-row"><div><h1>{path==='interviews'?'Make your next move.':'Find your event. Make your case.'}</h1><p className="intro">{path==='interviews'?'Interview preparation for university students, graduates, and your next career move.':'Competition-specific rehearsal for high-school DECA and FBLA members.'}</p></div><div className="edition">YOUR THINKING.<br/><b>YOUR NEXT LEVEL.</b></div></div>
 {path!=='interviews'&&<Tabs value={path} onValueChange={v=>changePath(String(v))}><TabsList className="path-tabs" aria-label="Practice path"><TabsTrigger value="deca">01 / DECA <span>60 events</span></TabsTrigger><TabsTrigger value="fbla">02 / FBLA <span>76 events</span></TabsTrigger></TabsList></Tabs>}
 {resumeCase&&lastEvent&&<section className="resume-practice"><div><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2>{resumeCase.title}</h2><p>{lastEvent.code||lastEvent.name} · Your work stays in this browser tab</p></div><button className="primary" onClick={()=>resume(resumeCase.id)}>Continue practice <ArrowRight size={17}/></button></section>}
 {preferencesNotice&&<p className="practice-notice" role="status">{preferencesNotice}</p>}
 <div className="catalog-controls"><label className="search-box"><Search size={18}/><input ref={searchInput} placeholder={path==='interviews'?'Search a role…':'Search an event, code, or skill…'} aria-label="Search events or roles" value={search} onChange={e=>setSearch(e.target.value)}/>{search?<button className="search-clear" aria-label="Clear search" onClick={()=>{setSearch('');searchInput.current?.focus()}}><X size={16}/></button>:<kbd aria-hidden="true">/</kbd>}</label>{path!=='interviews'&&<><Select value={cluster} onValueChange={v=>setCluster(String(v))}><SelectTrigger aria-label="Filter by sector" className="catalog-select"><SelectValue>{cluster==='all'?'All sectors':cluster}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">All sectors</SelectItem>{clusters.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={format} onValueChange={v=>setFormat(String(v))}><SelectTrigger aria-label="Filter by event format" className="catalog-select"><SelectValue>{format==='all'?'All event formats':format}</SelectValue></SelectTrigger><SelectContent><SelectItem value="all">All event formats</SelectItem>{formats.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></>}</div>
 <div className="catalog-refinements"><button className={savedOnly?'saved-filter active':'saved-filter'} aria-pressed={savedOnly} onClick={()=>setSavedOnly(!savedOnly)}><Bookmark size={15}/> Saved {path==='interviews'?'roles':'events'} <span>{favorites.filter(id=>all.some(e=>e.id===id)).length}</span></button>{(search||cluster!=='all'||format!=='all'||savedOnly)&&<button className="text-button" onClick={()=>{setSearch('');setCluster('all');setFormat('all');setSavedOnly(false)}}>Reset filters <X size={14}/></button>}<span>Your bookmarks stay on this device.</span></div><div className="catalog-count" aria-live="polite"><span>{visible.length} {path==='interviews'?'roles':'events'}{visible.length!==all.length?` of ${all.length}`:''}</span><span>{path==='interviews'?'24 drills per role · core, deep dive & pressure test':'2026–2027 international / national catalog'}</span></div>
 {visible.length?<div className="event-grid">{visible.map(e=><article className="catalog-event" key={e.id}><button className="event-card" onClick={()=>setEvent(e)}><span className="eyebrow">{e.code||e.cluster}</span><h3>{e.name}</h3><p>{e.format}</p><span className="card-action">{practiceCount(e)} practice options <ChevronRight size={17}/></span></button><button className="bookmark-event" aria-label={`${favorites.includes(e.id)?'Unsave':'Save'} ${e.name}`} aria-pressed={favorites.includes(e.id)} onClick={()=>toggleFavorite(e.id)}><Bookmark size={18} fill={favorites.includes(e.id)?'currentColor':'none'}/></button></article>)}</div>:<div className="empty-catalog"><Search size={28}/><h3>{savedOnly?'No saved events match':'No matching events'}</h3><p>Try the event name or code, or clear your filters.</p><button className="secondary-button" onClick={()=>{setSearch('');setCluster('all');setFormat('all');setSavedOnly(false)}}>Clear filters</button></div>}
 <Resources path={path}/>{history.length>0&&<section className="recent-practice"><div className="section-title"><div><h2>Your practice this session</h2><p>Temporary history in this browser tab. Export a debrief to keep it.</p></div></div>{history.slice(0,5).map(h=><button key={h.id} onClick={()=>{const [id,index]=(h.caseId||h.id).split(':');const e=catalog.find(e=>e.id===id);if(e){setEvent(e);setPath(e.path);setActive(getCases(e)[Number(index)])}}}><span>{h.title}</span><b>{h.score}/{h.max||100} recorded practice score</b><ArrowRight size={16}/></button>)}</section>}
 </>}</main>}<SiteFooter/><Tutorial path={guide} onClose={()=>setGuide(null)}/><Intro open={intro} onEnter={enterSite}/></div>
}
function Resources({path}:{path:Path}){return <aside className="resource-box"><div><span className="eyebrow">PREPARE FOR THE REAL FORMAT</span><h3>{path==='deca'?'Regionals → Provincials / States → ICDC':path==='fbla'?'District / Regional → State → NLC':'Know the role. Practice the conversation.'}</h3><p>{path==='deca'?'Local event availability and qualification vary. Ontario resources include provincial guidance; online events can follow a separate route. Always check the current rules with your advisor.':path==='fbla'?'Check your chapter’s event availability, grade eligibility and qualification rules. Introductory events may be restricted to grades 9–10. NLC is FBLA’s national conference.':'Use public employer guidance to understand the process. Rehearse out loud with another person to assess delivery, listening, and interaction.'}</p><p>Cases marked original are Casecraft rehearsals, not official past papers. Timings and scorecards are linked to their source and season. Interview difficulty settings are practice aids. {path!=='interviews'&&'Catalog checked against official 2026–2027 listings; guidelines can change.'}</p></div><div className="resource-links">{path==='deca'?<><a href="https://www.deca.org/compete" target="_blank" rel="noreferrer">DECA events & sample resources <ArrowUpRight size={16}/></a><a href="https://deca.ca/competitive-events/" target="_blank" rel="noreferrer">Ontario provincial resources <ArrowUpRight size={16}/></a></>:path==='fbla'?<><a href="https://www.fbla.org/high-school/competitive-events/" target="_blank" rel="noreferrer">FBLA official event catalog <ArrowUpRight size={16}/></a><a href="https://connect.fbla.org/files?folderId=344" target="_blank" rel="noreferrer">Event guidelines & rating sheets <ArrowUpRight size={16}/></a></>:<><a href="https://www.goldmansachs.com/careers/students/prepare" target="_blank" rel="noreferrer">Banking interview preparation <ArrowUpRight size={16}/></a><a href="https://www.mckinsey.com/careers/interviewing" target="_blank" rel="noreferrer">Consulting interview guidance <ArrowUpRight size={16}/></a><a href="https://www.janestreet.com/probability-markets/" target="_blank" rel="noreferrer">Probability & markets practice <ArrowUpRight size={16}/></a></>}</div></aside>}
