// Concise topic summaries. The linked official brief remains authoritative.
export const annualTopics:Record<string,string>={
'fbla-broadcast-journalism':'Report on a local business’s positive community contribution, supported by research, interviews and footage; the news segment is limited to two minutes.',
'fbla-business-ethics':'Analyze ethical leadership, stakeholder responsibilities and trust during the food-safety crisis described in the official background brief.',
'fbla-coding-programming':'Build a nonprofit volunteer-management program covering opportunities, scheduling, volunteer records and participation.',
'fbla-computer-game-simulation-programming':'Create a high-school sports-team management game or simulation involving season planning, resources, morale and strategic decisions.',
'fbla-data-analysis':'Use the specified civic-engagement data and additional research to recommend US community-impact priorities for the fictional technology company in the brief.',
'fbla-digital-animation':'Animate a product’s path through sourcing, production, transport, distribution, retail and customer use.',
'fbla-digital-video-production':'Produce a documentary about a local person, organization or initiative making a meaningful community contribution.',
'fbla-financial-planning':'Develop a financial recovery plan for the Smith family using the official household facts, including debt, education, caregiving, retirement and insurance needs.',
'fbla-financial-statement-analysis':'Analyze Costco using its fiscal 2025 annual report and other public information, then support recommendations for its long-term financial position.',
'fbla-future-business-educator':'Plan and teach an engaging business-education lesson on a chosen leadership skill, with meaningful learner application.',
'fbla-graphic-design':'Create a coherent identity and reopening asset package for a renovated local hotel.',
'fbla-introduction-to-business-presentation':'Explain how leaders can improve communication, inclusion and collaboration across workplace generations.',
'fbla-introduction-to-programming':'Build a digital ordering program for a chosen local business, including browsing, order handling and purchase totals.',
'fbla-introduction-to-public-speaking':'Explain how serving others develops leadership, using grounded examples.',
'fbla-introduction-to-social-media-strategy':'Use one social platform to promote the opening of a family mini-golf venue through a series of posts.',
'fbla-mobile-application-development':'Build a collaborative group-trip planning app covering scheduling, budgets, communication and shared trip information.',
'fbla-public-service-announcement':'Create a PSA encouraging practical household behaviors that reduce food waste.',
'fbla-public-speaking':'Explore how disciplined habits shape leadership, decisions and lasting achievement, rather than relying on talent alone.',
'fbla-social-media-strategies':'Develop a social strategy for the relaunch of a renovated outdoor-adventure rental business under new ownership.',
'fbla-supply-chain-management':'Recommend a last-mile strategy for a growing online retailer facing rising delivery costs, inconsistent fulfillment and declining customer satisfaction.',
'fbla-visual-design':'Design a welcoming, accessible visual information and navigation experience for a public library and technology center.',
'fbla-website-coding-development':'Code a functional website from scratch that solves an organizational resource, information, request or service-management need.',
'fbla-website-design':'Design an accessible, responsive website that organizes a community’s services, organizations, programs and resources.',
'deca-fce':'Consult with a business owner in their late fifties about retirement and options to sell, transfer or close the business while protecting financial security.',
'deca-htps':'Represent a tour wholesaler offering immersive group travel to an agency seeking experiences that appeal to younger travelers.',
'deca-pse':'Represent a combined AI customer-service and retail-analytics platform in a needs-led meeting with a regional retail-chain owner.',
};
export function topicFor(event:{id:string;format:string}){return annualTopics[event.id]||(event.format==='Business Operations Research'?'Partner with a local organization to investigate repeat engagement and customer loyalty, then use the findings to propose a retention strategy.':null)}
