import type {Event,PracticeCase,NumberCheck} from './engine';
type Company={id:string;name:string;source:string;guide:string;focus:string[]};
const employers:Record<string,Company>={
 'citadel-swe':{id:'citadel-swe',name:'Citadel',source:'https://www.citadel.com/careers/career-perspectives/our-engineering-interview-process/',guide:'Citadel’s campus engineering guide describes coding, data structures, algorithms and explanation of your approach, alongside discussion of projects and motivations.',focus:['Explain a technical project and its impact','Choose data structures and justify complexity','Test correctness before optimizing']},
 'jane-swe':{id:'jane-swe',name:'Jane Street',source:'https://www.janestreet.com/preparing-for-a-software-engineering-interview/',guide:'Jane Street describes collaborative coding problems in its software engineering interviews. Practice communicating your reasoning and developing a working solution with feedback.',focus:['Collaborate while solving a coding problem','Make invariants and edge cases explicit','Adapt your solution to a new requirement']},
 optiver:{id:'optiver',name:'Optiver',source:'https://www.optiver.com/join-us/stories/optiver-interview-tips-for-software-engineers/',guide:'Optiver provides software engineering interview preparation and encourages reflection on your engineering motivations and why the firm fits them.',focus:['Connect your engineering interests to the role','Explain correctness and performance trade-offs','Prepare thoughtful questions for engineers']},

 goldman:{id:'goldman',name:'Goldman Sachs',source:'https://www.goldmansachs.com/careers/students/prepare',guide:'Student hiring guidance describes an initial video interview and final interviews for selected candidates. Prepare a clear motivation for the division and evidence of your contribution.',focus:['Explain your interest in this division','Connect technical reasoning to a client decision','Prepare concise examples of your own contribution']},
 jpm:{id:'jpm',name:'JPMorganChase',source:'https://www.jpmorganchase.com/careers/how-we-hire',guide:'The firm says its process varies by position. Research the business and role, and prepare examples that explain your skills and experience.',focus:['Research the business and role','Make your assumptions and checks explicit','Practice communicating a difficult decision']},
 mckinsey:{id:'mckinsey',name:'McKinsey',source:'https://www.mckinsey.com/careers/interviewing',guide:'Consulting preparation includes problem-solving cases and personal-experience discussion. Practice structured analysis and detailed accounts of your own actions.',focus:['Clarify the objective before analysis','Synthesize evidence into a recommendation','Explain personal impact with specific actions']},
 bain:{id:'bain',name:'Bain',source:'https://www.bain.com/careers/hiring-process/interviewing/',guide:'Bain describes role-dependent interviews, behavioral discussion and consulting cases. Its guidance emphasizes logical structure, precision and creativity.',focus:['Structure a practical client problem','Check the arithmetic and implications','Explain why Bain and why this role']},
 jane:{id:'jane',name:'Jane Street',source:'https://www.janestreet.com/trading-interviews/',guide:'Trading interview guidance discusses probability, statistics, coding and data analysis. Rehearse explaining your reasoning while responding to new information.',focus:['State probability assumptions','Think aloud and use feedback','Check answers with a second method']},
 citadel:{id:'citadel',name:'Citadel',source:'https://www.citadel.com/careers/career-perspectives/our-quantitative-research-interview-process/',guide:'Quantitative research guidance emphasizes problem-solving and collaboration: clarify the question, explain trade-offs and work constructively with hints.',focus:['Define the model and its limitations','Discuss uncertainty and validation','Respond constructively to a hint']},
 amazon:{id:'amazon',name:'Amazon',source:'https://amazon.jobs/content/en/how-we-hire',guide:'Amazon publishes role-specific preparation alongside guidance on Leadership Principles and behavioral examples. Use concrete actions and results; confirm the format with your recruiter.',focus:['Start from the customer problem','Explain ownership with specific evidence','Support decisions with metrics and trade-offs']},
 microsoft:{id:'microsoft',name:'Microsoft',source:'https://careers.microsoft.com/v2/global/en/hiring-tips',guide:'Microsoft offers general hiring tips and technical preparation guidance. Practice explaining your approach, collaboration and learning; the exact assessment depends on the role.',focus:['Clarify requirements and customer needs','Explain collaboration and learning','Validate your solution and discuss limitations']}
};
const roleCompanies:Record<string,string[]>={banking:['goldman','jpm'],consulting:['mckinsey','bain'],quant:['jane','citadel'],'software-engineering':['citadel-swe','jane-swe','optiver','amazon','microsoft'],'product-management':['amazon','microsoft'],'data-analytics':['amazon','microsoft'],'data-engineering':['amazon','microsoft'],cybersecurity:['amazon','microsoft'],'corporate-finance':['amazon','microsoft'],'technical-sales':['amazon','microsoft']};
type Exercise={title:string;prompt:string;facts:string[];task:string;benchmark:string;followups:string[]};
// These are original fictional exercises, not reported interview questions or employer rubrics.
const exercises:Record<string,Exercise>={
 banking:{title:'Defend a valuation range',prompt:'A fictional client is considering acquiring a subscription-services company. Give the deal team a defensible initial view.',facts:['Normalized EBITDA is $24m; a comparable range is 8–10× EBITDA.','Debt is $65m and cash is $12m. Assume no other enterprise-to-equity adjustments.','A disputed $4m cost add-back is included in normalized EBITDA.'],task:'Calculate enterprise and equity value ranges, then show the impact of rejecting the add-back. Recommend diligence before discussing price.',benchmark:'Base EV is $192–240m and equity is $139–187m. Rejecting the add-back gives EBITDA $20m, EV $160–200m and equity $107–147m. Verify recurrence of the expense, cash restrictions, debt-like items and comparable quality. A multiple range is not a fairness opinion.',followups:['How would a customer concentration risk affect your analysis without arbitrarily changing the multiple?','The seller calls the cost one-time, but it appeared in three years. What evidence would resolve the disagreement?']},
 consulting:{title:'A growth plan that loses money',prompt:'A fictional service business wants to expand into a second city. Present a structured go/no-go recommendation.',facts:['Expected volume is 18,000 jobs per year at $80 revenue per job.','Variable cost is $50 per job; incremental annual fixed cost is $480,000.','Launching also requires $180,000 upfront. Capacity is 24,000 jobs annually.'],task:'Estimate operating profit and operating break-even volume. Distinguish recurring economics from launch cash needs, and design a pilot.',benchmark:'Contribution is $30 per job. Operating profit is $60,000; break-even is 16,000 jobs. First-year profit less the upfront outlay is −$120,000 as a simplified cash proxy, not accounting net income. Validate demand, utilization, cash timing and service quality. Stage spending around pilot evidence.',followups:['What happens at a 15% volume shortfall?','Which evidence would change your recommendation, and how would you collect it cheaply?']},
 quant:{title:'A signal worth paying for?',prompt:'Evaluate a fictional binary forecasting signal before using it in a decision.',facts:['The event occurs with prior probability 20%.','The signal is positive in 75% of event cases and 10% of non-event cases.','A contract pays $1 if the event occurs and $0 otherwise; after a positive signal it costs $0.60, with no other costs in the base case.'],task:'Compute the posterior probability after a positive signal and expected profit per contract. Explain what would invalidate the calculation.',benchmark:'Positive probability is .2×.75+.8×.10=.23. Posterior is .15/.23≈65.22%; expected profit at .60 is about $.0522. Base expected value is positive, but estimation error, selection bias, costs and correlated exposure matter. Validate the signal out of sample and avoid treating positive EV as guaranteed profit.',followups:['At a 10% prior, is the same contract attractive?','How would you estimate uncertainty if the reported rates came from a small sample?']},
 'software-engineering':{title:'Retries without duplicate orders',prompt:'Design a fictional checkout endpoint that remains correct when clients retry after a timeout.',facts:['Clients can retry the same request simultaneously.','The service writes orders to a database and calls an external payment provider.','A process may crash after charging the card but before storing the payment response.'],task:'Write code or precise pseudocode for the core request path. Define idempotency keys, state transitions, recovery and meaningful tests.',benchmark:'Bind an idempotency key to a request fingerprint with a unique constraint. Concurrent attempts must share an outcome, and reused keys with different payloads must fail. Use provider idempotency plus reconciliation for the crash window; a database transaction cannot atomically commit an unrelated payment API. Test retries, concurrency, mismatched payloads and recovery. State retention and expiry assumptions.',followups:['What should a retry receive while the first request is still in progress?','How would you recover if the payment provider offered no idempotency support?']},
 'product-management':{title:'Activation without a vanity metric',prompt:'A fictional team wants to replace a lengthy onboarding flow with a one-click setup.',facts:['Current activation is 40%; the proposed metric counts opening the home screen.','Support reports that customers often reach the home screen without completing setup.','The team can run a two-week experiment; long-term retention takes longer to measure.'],task:'Define a meaningful activation event, an experiment and guardrails. Explain the launch decision to engineering and support.',benchmark:'Define activation as demonstrated value, such as a successfully completed core task, rather than page arrival. Randomize at an appropriate stable unit, set primary and guardrail metrics before analysis, and check assignment integrity. Two weeks cannot establish long-term retention; use leading evidence with a staged rollout and a follow-up cohort readout. Include accessibility and setup error rates.',followups:['Conversion rises but support contacts double. How do you decide?','A stakeholder wants to stop the test after one good day. What do you explain?']},
 'data-analytics':{title:'The experiment with missing users',prompt:'A fictional experiment dashboard reports a conversion lift. Audit the evidence before recommending rollout.',facts:['10,000 users were assigned to each arm. Control has 800 purchases and treatment has 900.','The dashboard excludes 2,000 assigned treatment users whose tracking event was missing.','Missing events are concentrated on older phones.'],task:'Compute conversion using all assigned users and explain why the dashboard is biased. Propose a validity check and a decision.',benchmark:'Intent-to-treat conversion is 8% control and 9% treatment: +1 percentage point or 12.5% relative lift. Excluding treatment users produces 11.25% and a misleading comparison. Investigate tracking and outcome completeness, assignment balance, device segments and uncertainty; purchase counts may also be incomplete. Do not infer significance or justify launch from point estimates alone.',followups:['What if purchase outcomes are also missing for those users?','How would you avoid confusing a device-specific effect with a tracking bug?']},
 'data-engineering':{title:'Revenue that changes overnight',prompt:'A fictional revenue pipeline double-counts events when jobs are replayed. Design a reliable correction.',facts:['Events have an event ID, order ID, version, timestamp and amount.','Updates can arrive late and out of order; refunds are separate events.','Finance needs daily totals and a traceable restatement history.'],task:'Define the data grain, deduplication and update rules, then sketch SQL or pseudocode. Explain late data, reconciliation and recovery.',benchmark:'Define order state separately from an immutable event ledger. Deduplicate event IDs and resolve state using a documented version rule, not arrival order. Model refund grain explicitly to avoid fan-out joins. Rebuild affected partitions or upsert deterministically, preserve lineage and reconcile against the source. Tests should prove replay invariance, correct late updates and net revenue after refunds.',followups:['Two events share an ID but have different amounts. What happens?','How would you backfill a month without silently changing a published financial report?']},
 cybersecurity:{title:'Contain a stolen session',prompt:'A fictional employee reports a suspicious login immediately after approving an unexpected sign-in prompt.',facts:['The account has access to internal documents.','A valid session token may already exist even if the password is reset.','Logs show a large download, but the destination and contents are not yet confirmed.'],task:'Create a prioritized incident response plan covering containment, evidence, scope and communication. Explain what you would verify before making claims.',benchmark:'Use an approved channel to verify the report, revoke sessions/tokens and reset affected credentials as appropriate. Preserve logs and establish a timeline while containing access. Investigate downloads, permissions, persistence and other affected identities. Coordinate with incident owners and applicable legal/privacy teams; do not label unverified activity a confirmed data breach. Recover with monitoring and address the authentication weakness.',followups:['The account supports a critical production integration. How do you contain risk safely?','Which evidence would distinguish legitimate bulk access from exfiltration?']},
 'corporate-finance':{title:'Profit improves, cash tightens',prompt:'A fictional business unit proposes spending its apparent earnings increase on expansion.',facts:['Incremental annual operating profit is $400,000, including $100,000 depreciation.','Receivables increase $250,000, inventory increases $150,000 and payables increase $50,000.','Expansion capex is $300,000; ignore tax and financing for this exercise.'],task:'Build an incremental profit-to-cash bridge and recommend funding or phasing. Explain the assumptions to a non-finance leader.',benchmark:'Operating cash proxy is 400+100−250−150+50=$150k. After capex it is −$150k. Earnings growth does not fund the entire investment. Check timing, collections, inventory drivers, minimum cash and sensitivity before selecting a funding or phased investment plan. Do not present the simplified bridge as a full statutory cash-flow statement.',followups:['Collections improve by $100,000. Does that fund the plan?','What would you monitor monthly to catch a cash shortfall early?']},
 'technical-sales':{title:'Prove the migration business case',prompt:'A fictional prospect asks whether migrating a workload is worth the disruption.',facts:['Current annual operating cost is $240,000; proposed annual cost is $180,000.','One-time migration cost is $90,000. Assume constant costs and no discounting for the initial calculation.','The buyer requires a four-hour recovery objective and cannot accept unplanned downtime during peak season.'],task:'Calculate simple payback, discover missing requirements and propose a pilot with acceptance and rollback criteria.',benchmark:'Annual savings are $60k and simple payback is 1.5 years. This excludes growth, parallel operation, egress, training and risk. Clarify recovery time versus data-loss tolerance, workload dependencies and procurement constraints. Pilot a representative workload, test restore/failover, measure performance and cost, and agree a rollback window. Avoid promising resilience without evidence.',followups:['Actual annual cost is $210,000. How does the payback change?','The technical champion agrees but the budget owner does not. What is your next conversation?']}
};
export function companyTracksForRole(roleId:string):Company[]{return (roleCompanies[roleId]||[]).map(id=>employers[id])}
export function getCompanyCases(event:Event,companyId?:string):PracticeCase[]{
 if(event.path!=='interviews'||!exercises[event.id])return [];
 return companyTracksForRole(event.id).filter(co=>!companyId||co.id===companyId).flatMap(co=>{
 const base=engineeringExercises[co.id]&&event.id==='software-engineering'?engineeringExercises[co.id]:exercises[event.id];
 const context=`Original ${co.name} preparation exercise. All organizations, figures and situations in this scenario are fictional; this is not a reported ${co.name} interview question.`;
 return [{...base,id:`${event.id}:company-${co.id}-technical`,eventId:event.id,index:0,company:co,checks:[],numbers:companyNumbers[event.id]||[],facts:[context,...base.facts],task:`${base.task} Preparation lens: ${co.focus[1]}.`},
 {id:`${event.id}:company-${co.id}-experience`,eventId:event.id,index:1,company:co,title:`${co.name}: defend your contribution`,prompt:`Prepare a truthful experience story relevant to ${event.name}. Preparation focus: ${co.focus[0].toLowerCase()}.`,facts:[`Original Casecraft preparation prompt, not an official ${co.name} interview question.`,'Choose a real work, classroom, volunteer or personal project. Do not invent employment or results.','Separate your own decisions from team outcomes. An unsuccessful result is acceptable if you explain what you learned.','Aim for a two-minute spoken answer, then use the follow-ups to add detail.'],task:`Explain the situation, objective, your actions, evidence of results and what you would change. Connect the example to why this role at ${co.name} interests you, using something you verified in the employer’s public information.`,benchmark:'A strong answer identifies a specific challenge, constraints and personal decisions. Explain an alternative you considered, the evidence used and the impact with honest attribution. If metrics were unavailable, describe observable evidence and uncertainty. State a concrete lesson and a changed behavior. No single personal story is the model answer; delivery and truthfulness need human discussion.',followups:['Which decision was yours, and what would a teammate say you could have done better?',`How would you apply the lesson to this role while keeping this preparation focus in mind: ${co.focus[2].toLowerCase()}?`],checks:[],numbers:[]}];
 });
}

const engineeringExercises:Record<string,Exercise>={
 'citadel-swe':{title:'A rolling risk window',prompt:'Implement a rolling sum of signed position changes for a fictional risk monitor.',facts:['Input updates arrive in nondecreasing timestamp order, measured in milliseconds.','Each update has a unique ID and a signed integer delta; repeated IDs must not be counted twice.','After an update at time t, report the sum for timestamps in (t−1000, t].'],task:'Write code in your preferred language. Define duplicate handling, boundary behavior, memory use and time complexity. Include tests.',benchmark:'Use a queue and running sum, expiring entries with timestamp ≤t−1000 before reporting. Keep seen IDs according to an explicit retention contract: unbounded duplicate replay requires unbounded history or persistent deduplication; a bounded replay horizon permits expiration. Add each unique update once. Queue operations are amortized O(1); storage depends on event rate and the deduplication contract. Test negative deltas, exactly-boundary timestamps, same-time events, duplicates and an empty window.',followups:['How would out-of-order updates change the design?','How would you detect integer overflow and preserve exact financial units?']},
 'jane-swe':{title:'Build a dependency planner',prompt:'Write a planner for a fictional set of build tasks with prerequisites.',facts:['Input is a mapping from task names to prerequisite task names.','Return each task once with prerequisites before dependents.','Unknown prerequisites and cycles must produce useful errors; any valid order is acceptable.'],task:'Implement the planner and tests. Explain your data structures and how you would extend the solution while collaborating with an interviewer.',benchmark:'Validate references, then use DFS with unvisited/visiting/finished states or Kahn’s algorithm with indegrees. Include disconnected tasks and tasks with no prerequisites. Complexity is O(V+E); an unfinished visiting node or residual nodes after Kahn’s algorithm indicates a cycle. A cycle path is more useful than a generic failure. Test empty input, diamonds, unknown tasks, self-dependencies and multi-node cycles.',followups:['Now return groups that can run in parallel. What changes?','How would you produce deterministic ordering without promising linear time for sorting?']},
 optiver:{title:'Recover a market-data sequence',prompt:'Design a fictional consumer that maintains the latest quote without silently skipping updates.',facts:['Messages carry a sequence number, symbol, bid and ask.','Messages may be duplicated or arrive out of order; missing messages can be requested from a replay service.','The stream starts from a known snapshot with sequence number 100.'],task:'Write pseudocode for processing messages, handling gaps and recovery. Define correctness invariants, memory limits and tests before discussing latency.',benchmark:'Track the next expected sequence globally if the feed defines a global sequence. Apply only contiguous updates; ignore already-applied duplicates and buffer future messages within a bound. Request replay on gaps, drain contiguous buffered messages and resnapshot if recovery fails or buffers exceed limits. Never label incomplete state current. Clarify snapshot consistency and per-symbol versus global sequence contracts. Test duplicates, gaps, replay overlap and recovery failure.',followups:['How would you avoid an unbounded buffer during a long outage?','When is it safe to serve a quote after switching to a new snapshot?']}
};

const companyNumbers:Record<string,NumberCheck[]>={
 banking:[{label:'Base equity value, low end',answer:139,tolerance:.01,unit:'$m'},{label:'Adjusted equity value, high end',answer:147,tolerance:.01,unit:'$m'}],
 consulting:[{label:'Annual operating profit',answer:60000,tolerance:1,unit:'$'},{label:'Operating break-even volume',answer:16000,tolerance:1,unit:'jobs'}],
 quant:[{label:'Posterior event probability after a positive signal',answer:65.2174,tolerance:.01,unit:'%'},{label:'Expected profit per contract',answer:.052174,tolerance:.0001,unit:'$'}],
 'data-analytics':[{label:'Treatment conversion, all assigned users',answer:9,tolerance:.01,unit:'%'},{label:'Absolute conversion lift',answer:1,tolerance:.01,unit:'percentage points'}],
 'corporate-finance':[{label:'Operating cash proxy',answer:150000,tolerance:1,unit:'$'},{label:'Cash proxy after capex',answer:-150000,tolerance:1,unit:'$'}],
 'technical-sales':[{label:'Simple payback',answer:1.5,tolerance:.01,unit:'years'}]
};
