import type {Seed} from './content';
const s=(title:string,prompt:string,facts:string[],task:string,benchmark:string,followups:string[]):Seed=>({title,prompt,facts,task,benchmark,followups});
export const interviews:Record<string,Seed[]>={
banking:[
s('Walk me through depreciation','Technical / Accounting · Trace a $10 increase in depreciation through the three statements.',['Tax rate: 25%; assume the tax deduction applies immediately','No other changes; indirect cash-flow statement'],'Explain each statement and show that the balance sheet balances.','EBIT and pretax income fall $10; net income falls $7.50. Add back $10 depreciation, so operating cash flow and cash rise $2.50. Net PP&E falls $10; assets and retained earnings each fall $7.50.',['What if the company has no current taxable income?','Why is depreciation added back?']),
s('From enterprise value to equity value','Technical / Valuation · A buyer values a business at 12× EBITDA.',['EBITDA: $50m; debt: $140m; cash: $30m','Shares outstanding: 20m; no other adjustments'],'Calculate enterprise value, equity value and implied share price; explain the bridge.','Enterprise value is $600m; equity value $490m; implied price $24.50. Explain debt/cash claims and check for leases, minorities or other adjustments before treating a real transaction this simply.',['How does $10m additional excess cash change equity value?','Why not use net income with an EV multiple?']),
s('Defend your DCF assumptions','Technical / DCF · Value a business with one explicit forecast year.',['Year-one unlevered free cash flow: $10m','WACC: 10%; perpetual growth after year one: 2%','Cash flows occur at year-end; no non-operating adjustments'],'Calculate enterprise value and explain the major sensitivity.','Terminal value at year one is 10×1.02/(.10−.02)=$127.5m. EV=(10+127.5)/1.10=$125m. Growth must be below WACC; most value comes from the terminal assumption.',['What happens when WACC increases?','Why discount unlevered cash flow with WACC?']),
s('Is this acquisition accretive?','Technical / M&A · Evaluate an all-cash acquisition.',['Buyer net income: $100m; shares: 50m','Target net income: $20m; purchase price: $200m funded entirely with new debt','Debt interest: 6%; tax rate: 25%; ignore fees and purchase accounting'],'Calculate pro forma EPS and identify why accretion is not enough to recommend the deal.','After-tax interest is $9m; combined income $111m; EPS $2.22 vs $2.00, an 11% increase. Accretion does not prove positive NPV; assess price, integration and downside.',['What if interest rises to 10%?','What omitted accounting effects could change EPS?']),
s('A paper LBO under pressure','Technical / LBO · Assess a five-year buyout.',['Entry enterprise value: $500m; entry debt: $300m','Exit enterprise value: $600m; exit debt: $200m','No interim distributions or additional equity'],'Calculate equity multiple and approximate annual IRR; identify the return drivers.','Initial equity $200m; exit equity $400m; 2.0× MOIC and 2^(1/5)−1≈14.9% IRR. Returns come from enterprise-value growth and debt repayment; assess leverage downside and cash-generation assumptions.',['What if exit enterprise value is unchanged?','Why is MOIC not enough to compare holding periods?']),
s('Pitch a deal without overselling it','Commercial judgment / Deal discussion · A software company considers acquiring a smaller rival.',['Buyer seeks a new customer segment','Target customer churn has recently increased','Management proposes revenue synergies but has no tested cross-sell data'],'Present a balanced deal thesis, valuation approach and diligence priorities.','Connect strategic fit to verifiable value drivers, separate base value from unproven synergies and test churn/customer concentration. State what would make you walk away.',['What information would you request first?','How would you value uncertain synergies?']),
s('Why investment banking?','Behavioral / Motivation · Give a credible answer to the role-motivation question.',['Use genuine experience and knowledge of the work','No prestige or compensation claims need to carry the answer'],'Write a 90-second answer connecting your interests, evidence and role understanding.','Explain why transaction and analytical work interests you, give a real example and show awareness of the work and learning demands. Generic enthusiasm without evidence is weak; do not invent an internship.',['Why banking instead of consulting?','What part of the job would challenge you most?']),
s('The number in the pitchbook is wrong','Behavioral / Judgment · You find a material error shortly before a client meeting.',['The deck has already been sent to a senior colleague','You are not yet certain which source is correct','There are 20 minutes before the meeting'],'Explain your immediate actions, communication and prevention plan.','Verify the discrepancy quickly, escalate clearly with impact and a proposed correction, and preserve version control. Do not hide the error or silently change an uncertain number.',['What if the senior colleague says to ignore it?','How would you prevent a repeat?'])],
consulting:[
s('Revenue grew. Profit did not.','Case / Profitability · Diagnose a café’s declining profit.',['Last month: 10,000 drinks at $5; variable cost $2 per drink; fixed costs $20,000','This month: 12,000 drinks at $5; variable cost $2.50; fixed costs $24,000'],'Calculate profit in both periods, explain the drivers and recommend next steps.','Profit falls from $10,000 to $6,000. Volume adds $6,000 at old margin, variable-cost increase subtracts $6,000 and fixed-cost growth subtracts $4,000. Investigate causes and customer effects before cutting costs blindly.',['What price restores last month’s profit at current volume?','What data would distinguish waste from supplier inflation?']),
s('Size a market from first principles','Case / Market sizing · Estimate annual café coffee purchases in a small city.',['Population: 500,000; 60% adults','Assume 40% of adults buy café coffee','Assume three purchases per buyer per week and 50 weeks per year'],'Build the estimate, check units and explain sensitivity and missing segments.','500,000×.6×.4×3×50=18m annual purchases. State assumptions, distinguish purchases from dollars, check external plausibility and avoid double-counting visitors.',['What is the dollar market at $4 per purchase?','Which assumption would you research first?']),
s('Should we enter this market?','Case / Market entry · A subscription company considers a new geography.',['Addressable customers: 100,000; expected first-year share: 2%','Annual revenue/customer: $300; variable cost: $120','Launch fixed costs: $500,000; ignore acquisition timing'],'Evaluate first-year economics and a staged go/no-go decision.','2,000 customers produce $360,000 contribution and a $140,000 loss. Break-even is about 2,778 customers. Validate acquisition cost, retention, localization and timing; first-year loss alone is not decisive.',['What would make the pilot a success?','How would competitor response affect the model?']),
s('A price increase with a catch','Case / Pricing · A company proposes a 10% price increase.',['Current price: $100; variable cost: $60; sales: 10,000 units','Expected unit-volume decline: 15%','Fixed costs unchanged'],'Compare contribution and find the maximum volume decline that preserves it.','Current contribution $400,000; proposed $425,000. Break-even volume 8,000, a 20% decline. Discuss elasticity uncertainty, segments, competition and longer-term retention.',['How would you run a pricing test?','What if variable cost rises to $65?']),
s('Find the actual bottleneck','Case / Operations · A factory wants to increase output.',['Station A capacity: 120 units/hour; B: 80; C: 100','Demand: 110/hour; all units pass through each station','Upgrading B to 105/hour costs $20,000'],'Estimate throughput change and an investment decision process.','Current throughput is at most 80/hour. After upgrading B, C limits it to 100/hour, a 20/hour increase. Value incremental contribution over realistic operating hours and include downtime/quality constraints.',['What is the next bottleneck?','What information is needed to calculate payback?']),
s('Make a recommendation in 60 seconds','Case / Synthesis · Present a recommendation with incomplete evidence.',['Pilot increased conversion from 10% to 12%','Only 200 visitors participated; no randomized control','Full rollout costs $100,000'],'Give a concise recommendation, evidence, caveat and next decision gate.','Acknowledge limited evidence and confounding, quantify the observed change without claiming causality, and propose a proportionate controlled test. State an explicit decision and what would change it.',['What would you say if the CEO demands a yes or no?','How would you choose a success threshold?']),
s('Influence without authority','Behavioral / Personal experience · Describe a time you changed a team’s direction.',['Use a real example','Focus on a disagreement, your actions and the outcome'],'Write an answer with specific interpersonal actions and reflection.','Describe others’ interests fairly, what you personally did, evidence used and the resulting change. Avoid taking credit for everything or portraying disagreement as incompetence.',['What would the other person say happened?','What would you do differently?']),
s('A setback worth learning from','Behavioral / Resilience · Tell an interviewer about a failure.',['Choose a real setback with meaningful stakes','An unresolved outcome is acceptable if you are honest'],'Explain your contribution to the problem, recovery and lasting change.','Take proportionate ownership, explain concrete recovery actions and demonstrate learning applied later. A disguised strength or invented success does not answer the question.',['How did you seek feedback?','What evidence shows you changed?'])],
quant:[
s('A conditional probability trap','Technical / Probability · You roll two independent fair six-sided dice.',['You are told that at least one die shows six'],'Find the probability that both dice show six and explain the sample space.','There are 11 ordered outcomes with at least one six; one has two sixes. Probability is 1/11≈0.090909. Distinguish this condition from observing a specifically identified die is six.',['What if you are told the first die is six?','Why does the way information is revealed matter?']),
s('The value of a reroll','Technical / Expected value · Roll a fair six-sided die for a payout equal to its face.',['You may accept the roll or reroll once','The second roll must be accepted; there is no fee'],'Find the optimal policy and expected payout.','A reroll is worth 3.5, so reroll 1,2,3 and keep 4,5,6. Expected payout=(3×3.5+4+5+6)/6=4.25. Compare conditional continuation value rather than intuitively chasing six.',['How does a $1 reroll fee change the policy?','How would you solve with two rerolls?']),
s('A positive signal is not a certainty','Technical / Bayes · Evaluate a rare-event detector.',['Event prevalence: 1%','Sensitivity: 90%; false-positive rate: 5%'],'Calculate the chance of a true event given a positive result.','P(event|positive)=.009/(.009+.0495)=2/13≈15.38%. Use base rates and distinguish sensitivity from posterior probability.',['What changes at 10% prevalence?','How could you explain the result with a population table?']),
s('Estimate before you test','Technical / Statistics · Compare two conversion rates.',['Control: 100 conversions out of 1,000','Treatment: 120 out of 1,000','Assume randomized independent observations'],'Estimate the effect, uncertainty and appropriate decision.','The lift is 2 percentage points or 20% relative. Unpooled SE≈sqrt(.1×.9/1000+.12×.88/1000)=.014; approximate 95% difference interval −.0074 to .0474. Evidence is not conclusive at a conventional two-sided 5% level.',['What if the test was stopped when significance first appeared?','Why is practical significance different from statistical significance?']),
s('Quote a market under uncertainty','Technical / Market making · Estimate a hidden fair value and quote a two-sided market.',['Your current estimate is 100','You are already long 50 units','A better-informed trader may trade against you'],'Propose a quote and size, then explain inventory and adverse-selection risks.','There is no single correct spread without risk parameters. Explain uncertainty, shift quotes to manage long inventory, limit size and update beliefs after trades. A tight quote is not automatically profitable.',['What do repeated sells to your bid tell you?','How would new public information change the quote?']),
s('Delta is not a guarantee','Technical / Risk · Hedge a position in calls.',['You are long 100 call contracts; each controls 100 shares','Each option delta is 0.60','Assume the same underlying and no other positions'],'Calculate the initial share hedge and explain its limitations.','The position has +6,000 share-equivalent delta; short 6,000 shares for an initial delta-neutral hedge. Delta changes with price/time/volatility; gamma, costs and discrete rebalancing remain.',['What if delta rises to 0.70?','Does delta neutrality eliminate all risk?']),
s('Stream the best two values','Technical / Coding · Process a stream of numbers.',['Return the two largest distinct values','Use constant extra memory','Handle fewer than two distinct values'],'Write code or pseudocode, explain complexity and provide edge cases.','Track two distinct maxima with well-defined empty states, updating in one pass. O(n) time/O(1) space; handle negatives, duplicates and undersized input. Code is not executed in this written drill.',['What changes if duplicate values count?','How would you test with all negative numbers?']),
s('When your model loses money','Behavioral / Research judgment · A strategy fails out of sample.',['Backtest results looked strong','Several parameter sets were tried','Trading costs were estimated optimistically'],'Explain how you would investigate and decide whether to continue.','Check leakage, multiple testing, regime differences and realistic transaction costs before retuning. Define holdout discipline and stop criteria; acknowledge uncertainty and communicate losses honestly.',['What evidence would make you abandon the idea?','How would you avoid contaminating a new holdout?'])],
};
