import type {Seed} from './content';
// Each family has a core problem and two independently selectable interviewer probes.
type Family=[string,string,string,string,string,string];
const families:Record<string,Family[]>={
coding:[
['Duplicate payments','A payment API receives the same checkout request twice after a timeout. The processor may have charged the first request.','Design an idempotent request flow and write pseudocode for the critical state transitions.','What happens when two workers receive the same key simultaneously?','How would you recover a request stuck between provider success and local commit?','Use a unique idempotency key with a request fingerprint and atomic state changes. Persist the provider reference, return the stored result on retries, and reconcile uncertain outcomes. A timeout is not proof that no charge occurred.'],
['Top K in a stream','A service receives product IDs continuously and must return the ten most frequent IDs. Memory fits all distinct IDs but not all events.','Choose data structures and analyze update and query complexity.','How does your design change if only a fixed memory budget is available?','How would you test tie-breaking and highly skewed traffic?','Maintain exact counts per ID; a heap or partial selection answers top K. State whether the heap is maintained continuously or rebuilt at query time. Fixed-memory sketches are approximate and require stated error bounds; test ties, empty input and repeated IDs.'],
['Expiring cache','Design a cache with a fixed entry count and a time-to-live per entry. Reads may occur concurrently with eviction.','Write the read and write behavior, including expiration and eviction policy.','How do you stop a hot expired key from causing a backend stampede?','What clock and concurrency assumptions make your design safe?','Distinguish TTL expiry from capacity eviction. Check expiry on reads, protect shared state, and use request coalescing or bounded refresh to avoid a stampede. Prefer monotonic duration tracking where appropriate and test expiration boundaries.'],
['Reservation service','A ticket platform must sell 500 seats without overselling while users hold seats for five minutes.','Model seat states and transactional booking behavior.','What happens when payment completes after a hold expires?','How would you handle a queue during a large launch?','Use atomic state transitions, ownership tokens and hold expiry. Define the payment/expiry race and compensation explicitly. Admission control and queueing protect capacity; retries must be idempotent. Availability counters alone do not prevent overselling.'],
['Slow endpoint','An endpoint has p50 latency of 80 ms and p99 of 2 seconds after a release. Average CPU is unchanged.','Describe a diagnostic sequence and a safe mitigation.','What if traces show only one downstream service is slow?','How would you prove the fix improved tail latency?','Compare deployment cohorts and inspect traces, dependency latency, queueing and connection pools. Bound retries and consider rollback or isolation. Measure percentile latency and errors under representative load rather than relying on averages.'],
['Schema migration','You must rename a heavily used database field without a coordinated deployment of all clients.','Plan a backward-compatible migration.','How would you detect that a supposedly retired client still uses the old field?','What is the rollback plan after backfilling half the table?','Use expand-and-contract: introduce the new field, support both versions, backfill idempotently, validate and retire only after usage evidence. Avoid destructive schema changes before clients migrate. Track divergence and rollback boundaries.'],
['Dependency ordering','A build system receives tasks and directed prerequisite edges. It must produce a valid execution order.','Write an algorithm and explain its complexity.','How do you report a cycle usefully to a developer?','How would you schedule independent tasks across four workers?','Topological sorting with indegrees or DFS runs in O(V+E). Detect when no valid order exists and identify a cycle or blocked subgraph. Parallel scheduling must respect completed prerequisites and handle failed tasks.'],
['A disputed code review','A teammate proposes a faster implementation that is harder to maintain and has no benchmark. A release is due tomorrow.','Explain how you would resolve the disagreement and make a release decision.','What evidence would justify accepting the added complexity?','How would you respond if your preferred solution proved slower?','Clarify the performance requirement, benchmark representative workloads and compare maintenance risks. Seek a reversible decision and targeted tests. Describe your own communication and learning rather than inventing a successful outcome.']
],
projects:[
['Activation falls','A collaboration app sees sign-ups rise 20% but seven-day activation fall from 40% to 30%. Activation means completing a shared project.','Diagnose the change and recommend the first investigation.','What if paid acquisition brought in a different user segment?','Which experiment would distinguish onboarding friction from weak product fit?','Define cohorts and denominators, validate instrumentation, and segment acquisition and intent. A changing mix can move the aggregate without a worse experience. Design an experiment tied to a specific failure point with retention guardrails.'],
['Choose the roadmap','A team can complete one project: enterprise SSO, faster onboarding, or an offline mode. Sales, growth and existing customers each favor one.','Build a prioritization approach and explain the decision inputs.','How would a signed enterprise commitment change the ranking?','How would you measure opportunity cost after delivery?','Compare user needs, strategic fit, expected impact, confidence and full effort. Separate contractual obligations from speculative revenue. Explain assumptions and dependencies, and define a measurable outcome rather than scoring projects mechanically.'],
['Pricing a new tier','A software company wants to introduce a paid automation tier without hurting its existing subscription business.','Design customer research and a launch test.','What if power users move to the cheaper tier?','Which guardrails would stop the experiment?','Research willingness to pay and segment needs; compare incremental contribution and cannibalization. Test packaging and pricing while monitoring retention, support burden and migration. Revenue alone is insufficient if margins or long-term value fall.'],
['Marketplace cold start','You are launching a marketplace for local business services with few buyers and few suppliers.','Choose a narrow initial market and a liquidity strategy.','What if suppliers join but do not respond to requests?','When would you expand to a second city?','Concentrate on a tractable segment, define successful matching and response time, and manually learn where transactions fail. Incentives should improve completed, high-quality matches. Expansion depends on repeatable liquidity and unit economics.'],
['Search relevance','Users complain that search returns popular items rather than what they intended to find.','Define success and propose a ranking improvement.','How would you evaluate queries with no clicks?','How would a short-term click gain hide worse outcomes?','Combine relevance judgments with task completion and downstream satisfaction. Segment query intent and handle zero-result or abandoned sessions. Avoid treating every click as success; guard against clickbait, latency and poor conversion.'],
['Responsible feature launch','A draft-writing feature sometimes invents facts. Customers want a faster launch; support worries about trust.','Scope a useful first release and an evaluation plan.','Which use cases would you exclude initially?','What evidence would justify broader rollout?','Identify failure severity by use case, set measurable quality thresholds and provide editable drafts with appropriate review. Evaluate representative examples and regressions. Expand only when observed performance supports the intended task.'],
['Metric disagreement','Finance measures paying accounts; product measures active seats. Both report growth and disagree about business health.','Create a shared metric framework.','How do you handle customers with many inactive paid seats?','What should the executive dashboard show?','Define account, seat, activity window and revenue recognition separately. Connect leading usage indicators with renewal and contribution outcomes. Preserve distinct metrics rather than collapsing different questions into one headline.'],
['An unsuccessful launch','An interviewer asks about a product decision you made that did not work.','Use a real example to explain your judgment, contribution and learning.','What signal should have changed your mind earlier?','What did you change in your next decision process?','Use a real event with a clear decision and evidence. Distinguish your actions from the team outcome, acknowledge uncertainty and explain a specific process improvement. Do not fabricate metrics or shift blame.']
],
data:[
['A misleading average','Product A delivers in 2 days and B in 4 days. Last month the mix was 50/50; this month it is 80/20. Neither product improved.','Calculate the new average and explain the apparent change.','How would you present a mix-adjusted trend?','What causal claim can you make from this information?','The average moves from 3 to 2.4 days purely due to mix. Report within-product trends or use fixed weights for comparison. The aggregate change does not demonstrate a delivery-process improvement.'],
['Experiment decision','Control converts 400 of 10,000 visitors; treatment converts 440 of 10,000. Assignment is random by user.','Calculate absolute and relative lift and outline an inference plan.','What changes if users appear in both arms?','Why can repeatedly checking for significance mislead the team?','Absolute lift is 0.4 percentage points and relative lift is 10%. Quantify sampling uncertainty and predefine a decision rule. Cross-arm exposure breaks the clean assignment assumption; repeated looks require an appropriate sequential design.'],
['A duplicated revenue join','Orders has one row per order; order_items has multiple rows per order. A joined report sums order-level revenue.','Explain the error and write a safe SQL approach.','How would refunds alter the definition?','Which reconciliation tests would you add?','The join multiplies order revenue by item count. Aggregate at the correct grain before joining or sum appropriately allocated item values. Define refunds and dates explicitly, then reconcile counts and totals to the source.'],
['Retention cohorts','A subscription team wants a 30-day retention chart, but many new users joined within the past week.','Define the cohort and denominator correctly.','How would seasonality change your interpretation?','What is the difference between user retention and revenue retention?','Only include cohorts with sufficient observation time for a 30-day measure, or use a method that handles censoring. Define active behavior and dates. User counts and retained revenue answer different questions.'],
['Model leakage','A churn model uses a field populated when an account closes. Offline accuracy is excellent.','Explain the leakage and redesign validation.','What if the field is available one day before closure?','How would you check the complete feature pipeline for leakage?','Features must be available at the actual prediction time and useful lead time. Use point-in-time joins and time-based splits, compare a baseline and review each feature lineage. A near-outcome signal may be too late for intervention.'],
['Missing survey answers','A customer survey has a 12% response rate. Highly engaged customers respond most often.','Assess representativeness and propose a better collection plan.','When would weighting help, and when would it fail?','How would you communicate uncertainty to leadership?','Nonresponse can bias estimates. Compare observed respondents and the target population, recruit underrepresented groups and avoid claiming weighting fixes unobserved selection. Report assumptions, response rates and plausible sensitivity.'],
['Fraud thresholds','A detector flags 100 transactions, 20 of which are fraud. It misses another 30 fraudulent transactions.','Calculate precision and recall and discuss threshold choice.','How would different review costs change your recommendation?','What should happen if fraud patterns drift?','Precision is 20% and recall is 40%. Select thresholds using error costs, review capacity and customer friction, not accuracy alone. Track drift and delayed labels, and evaluate performance on representative future periods.'],
['Dashboard trust','An executive dashboard disagrees with a finance report after a timezone change.','Plan a reconciliation and communicate the issue.','How do late-arriving events complicate daily totals?','What data contract would prevent recurrence?','Compare timezone boundaries, event versus processing time, grain and metric definitions. Reconcile a small sample before the full period. Document refresh rules and late-data policy; clearly mark unreliable metrics while investigating.']
],
office:[
['Late events pipeline','Orders arrive out of order and may be delivered twice. Finance needs reliable daily totals.','Design ingestion, deduplication and late-data handling.','How would you revise a report after a week-old event arrives?','What distinguishes exactly-once delivery from exactly-once effects?','Use stable event IDs and idempotent writes. Track event time separately from processing time, define lateness and corrections, and reconcile outputs. End-to-end effects depend on every sink and transaction boundary.'],
['Slow warehouse query','A dashboard scans two years of events for a daily report. Most users filter by date and customer.','Diagnose and improve query cost without changing results.','How would skewed customers affect the plan?','How do you prove the optimization preserved correctness?','Inspect the query plan and scanned bytes. Partition or cluster based on actual access, prune early and consider an aggregate table at the correct grain. Compare counts, nulls and totals on representative data.'],
['Changing schemas','A producer changes amount from integer cents to decimal dollars without warning.','Design detection and a safe response.','How would you backfill already-corrupted records?','What compatibility rule should the producer follow?','Validate schema and semantic units, quarantine suspect data and stop incorrect aggregates. Backfill from a trustworthy source with version-aware transforms. A syntactically valid number can still violate the data contract.'],
['Customer dimensions','A customer moves regions. Analysts need both historical and current-region revenue views.','Model the dimension and joins.','How do you handle retroactive corrections?','Which checks catch overlapping effective-date ranges?','Use a history-preserving dimension with effective intervals and a current view. Join facts to the region at event time for historical analysis. Define corrections carefully and test interval overlap, gaps and uniqueness.'],
['Backfill under load','You must reprocess 18 months of events while the live pipeline continues.','Plan an idempotent and observable backfill.','How do you prevent double-counting where live and backfill overlap?','What rollback boundary would you choose?','Partition work, isolate resource usage and write versioned or idempotent outputs. Reconcile counts and checkpoints before swapping consumers. Make overlap semantics and rollback explicit rather than relying on execution order.'],
['Access to sensitive data','An analyst needs aggregate customer behavior, but a raw table includes personal identifiers.','Design a least-privilege data product.','How would you audit whether access is appropriate?','What happens when an upstream deletion must propagate?','Expose only needed fields and aggregates with access controls and audit trails. Maintain lineage and a tested deletion/retention process. Masking a name alone may not remove re-identification risks.'],
['Streaming or batch','Operations wants minute-level updates while finance needs accurate daily closes.','Choose an architecture and explain the trade-offs.','What happens when the streaming path falls behind?','How would you keep two processing paths consistent?','Separate freshness from finality. Use shared definitions, explicit watermarks or reconciliation, and a fallback for delayed data. Evaluate operational cost and failure recovery before choosing a complex dual path.'],
['A broken dependency','A source job succeeds with zero rows and downstream jobs publish an empty dashboard.','Design quality gates and incident recovery.','How would you avoid false alarms on legitimately quiet days?','What information belongs in the incident update?','Success status does not prove data completeness. Test volume, freshness and business invariants with season-aware thresholds. Stop unsafe publication, restore a known-good view and communicate scope and recovery confidence.']
],
security:[
['Suspicious sign-in','A finance user reports an unexpected sign-in notification. Logs show a new device and a large file download.','Prioritize defensive investigation and containment.','What would you do if the user is travelling?','How do you preserve evidence while limiting exposure?','Verify through a trusted channel, scope session and file activity, revoke suspect sessions as appropriate and preserve relevant logs. A new location alone is not proof of compromise; prioritize corroborating evidence and business impact.'],
['Leaked application secret','A developer accidentally commits a service credential to a shared repository.','Plan remediation and assess the exposure.','Why is deleting the commit insufficient?','How would you prevent a repeat without blocking development?','Revoke or rotate the credential, identify permissions and usage, and review access during the exposure window. Removing history does not invalidate copied secrets. Use managed secrets, scanning and least privilege.'],
['Overpowered service account','A reporting application can read and modify every production table even though it only needs aggregates.','Propose a safer permission model and rollout.','How do you discover undocumented dependencies?','What telemetry confirms the new policy works?','Map actual access needs, introduce narrower roles and read-only views, and stage changes with denied-access monitoring. Separate accounts by purpose and preserve a reviewed rollback path without leaving broad permissions indefinitely.'],
['Ransomware readiness','A company has backups but has never tested a full restore. Critical systems share the same administrative account.','Prioritize resilience improvements.','How would you choose recovery time and recovery point targets?','What should a recovery exercise demonstrate?','Map critical services and dependencies, isolate backup access and test restoration to clean infrastructure. Define acceptable downtime and data loss with owners. A successful backup job is not proof of recoverability.'],
['Vendor access','A vendor requests permanent administrator access to troubleshoot a production integration.','Design a controlled support process.','What if the vendor refuses a restricted role?','Which evidence should be retained after the session?','Use approved, time-limited, least-privilege access with logging and a clear task scope. Explore a supervised session or scoped diagnostic data. Escalate unmet requirements; do not share unrestricted credentials.'],
['Alert fatigue','A detection rule generates 5,000 daily alerts and analysts investigate only 200.','Improve triage without hiding important incidents.','How would you evaluate a proposed suppression rule?','Which measures distinguish less noise from missed incidents?','Analyze true positives, duplicate causes and severity; tune with labeled examples and validation. Track coverage, response time and false negatives where observable. Alert count reduction alone is not evidence of better detection.'],
['Threat model a file upload','A business application accepts customer documents and makes them available to employees.','Identify trust boundaries and defensive controls.','How do you prevent one customer from reading another customer’s files?','What should happen when file inspection is unavailable?','Validate authorization on each object, constrain uploads and storage permissions, and isolate inspection. Define safe failure behavior and audit access. File extension checks alone do not establish safety.'],
['Security disagreement','A release owner wants to defer a security fix because the feature is commercially important.','Describe a risk-based decision process.','What evidence would justify a temporary exception?','How do you ensure the exception does not become permanent?','Explain exploitability, exposure and impact in the product context. Consider compensating controls, a accountable owner and an expiry date. Record the decision and verify remediation rather than treating acceptance as elimination of risk.']
],
accounting:[
['Budget variance','A team budgeted 1,000 units at $40 variable cost. Actual output is 1,200 units at $43.','Separate volume and unit-cost effects against the original budget.','What would a flexible budget show?','Which variance should the operating manager investigate first?','Original cost is $40,000 and actual cost $51,600. At actual volume the flexible budget is $48,000: $8,000 volume effect and $3,600 rate effect. Investigate drivers before assigning responsibility.'],
['A capital investment','A project costs $100,000 now and returns $40,000 at each of the next three year ends. Use a 10% discount rate and no terminal value.','Estimate NPV and recommend a decision framework.','Why can payback conflict with NPV?','How would you test the most uncertain assumption?','Discount each cash flow: present value is about $99,474 and NPV about -$526. Payback ignores discounting and later cash flows. Examine forecast risk, opportunity cost and strategic constraints rather than rounding a marginal result into certainty.'],
['Runway planning','A startup has $900,000 cash and net monthly cash burn of $100,000, assumed constant before any intervention.','Calculate runway and propose a cash-planning process.','What if receivables collections are delayed by one month?','How would you distinguish a sustainable saving from a delayed payment?','Simple runway is nine months. Build a dated cash forecast and stress collections and commitments. Distinguish recurring cost reductions from timing shifts and monitor cash conversion rather than EBITDA alone.'],
['Working capital release','Annual credit sales are $3.65m and average receivables are $500,000. Use 365 days.','Estimate DSO and identify ways to improve collections responsibly.','How would seasonality distort the estimate?','When could a discount destroy more value than it releases?','Average daily sales are $10,000 and DSO is 50 days. Compare like periods and analyze aging and disputes. Evaluate discount cost against funding and credit risk; the ratio alone does not identify a collection failure.'],
['Contribution or revenue','Product A sells for $100 with $70 variable cost; B sells for $80 with $40 variable cost. Both use one hour of the bottleneck.','Prioritize scarce capacity under these assumptions.','What if B takes twice as long at the bottleneck?','Which constraints could overturn a contribution-based ranking?','A contributes $30 per hour and B $40, so B ranks first initially. At two hours B contributes $20 per hour. Consider demand, commitments and relevant opportunity costs; do not allocate fixed cost arbitrarily to the marginal decision.'],
['Forecast credibility','Sales predicts 30% growth despite a flat pipeline and rising churn. Leadership asks you to use the target as the forecast.','Build a defensible forecast and communicate the gap.','How would you create a bridge from current run rate to target?','What evidence would cause an upward revision?','Separate a target from an evidence-based forecast. Use pipeline conversion, retention, pricing and timing drivers; show scenarios and accountable actions. Document assumptions and update against observed leading indicators.'],
['Lease or buy','Two equipment options provide identical service, but their timing, maintenance obligations and residual values differ.','Explain how you would compare them financially.','How do financing terms affect comparability?','What downside scenario should management see?','Compare incremental after-tax cash flows consistently using a suitable discount framework, including maintenance, residual risk and flexibility. Do not compare a monthly lease payment with purchase price alone. Verify assumptions before calculating.'],
['An uncomfortable correction','You find an error in a forecast already presented to leadership. Correcting it would reverse a spending recommendation.','Explain your immediate actions and communication.','How would you assess whether other reports share the error?','What control would reduce recurrence?','Verify the issue and scope, promptly disclose the correction and explain decision impact. Trace dependencies and preserve a clear version history. Own the error without speculation and add a targeted reconciliation or review control.']
],
sales:[
['Discovery before demo','A prospect asks for a demo of your workflow software but has not explained its business problem.','Run a discovery conversation and decide what to demonstrate.','What if the buyer refuses to share a budget?','How would you distinguish user enthusiasm from purchasing authority?','Clarify current workflow, pain, impact, stakeholders and decision process. Ask permission to tailor the demo. Budget uncertainty is a discovery gap, not a reason to invent ROI or assume the contact can buy.'],
['Build the business case','A tool costs $24,000 annually and may save 1,000 staff hours. The buyer values an hour at $35, but not all freed time reduces spending.','Present a transparent value case.','How does redeployed time differ from cash savings?','What would a pilot need to measure?','Gross time value is $35,000 and net illustrative value $11,000 before implementation costs, but neither proves cash savings. Separate capacity benefits from reduced expenditure and validate adoption and time saved.'],
['The price objection','A prospect says a competitor is 20% cheaper but will not share the full comparison.','Respond without immediately discounting.','When would a discount be commercially justified?','How would you compare total cost fairly?','Clarify the buying criteria and comparable scope, implementation, support and risk. Explore fit and measurable value before negotiating. Do not make unsupported competitor claims; any concession should have a clear rationale and approval.'],
['Technical proof of concept','A buyer wants a proof of concept involving sensitive customer data and an integration your team has not tested.','Define scope, success criteria and safeguards.','What if the buyer insists on production data immediately?','How do you avoid an open-ended unpaid engineering project?','Agree a bounded technical test, use approved data and security controls, and involve engineering. State unverified capabilities and acceptance criteria. Document time limits, responsibilities and the decision after the trial.'],
['A renewal at risk','A customer uses only one of five purchased modules and reports slow support. Renewal is in 60 days.','Build a retention plan grounded in customer outcomes.','What if a larger discount does not address the complaint?','Which signals indicate genuine recovery?','Investigate adoption barriers and unresolved issues, assign owners and agree measurable recovery milestones. Tie renewal to delivered value rather than activity counts or price alone. Escalate promises that the team cannot meet.'],
['Conflicting stakeholders','IT likes your architecture; finance questions value; users fear a disruptive migration.','Map the decision and adapt your communication.','What happens if the sponsor leaves the company?','How would you identify a genuine decision deadline?','Understand each stakeholder’s criteria and influence, validate the process and build a shared business case. Reduce single-sponsor dependence and distinguish external deadlines from sales targets. Avoid bypassing legitimate objections.'],
['Pipeline honesty','A sales manager wants a large deal marked committed, but procurement and security reviews have not started.','Give an evidence-based forecast and next steps.','Which milestones would justify upgrading confidence?','How do you communicate risk without abandoning the opportunity?','Use verified buying steps, owners and timing to assess confidence. Keep aspiration separate from forecast categories. Advance procurement and security discovery, document dependencies and avoid inventing certainty to meet a target.'],
['An unsupported promise','During a call, a teammate promises a feature that is not on the committed roadmap.','Repair the expectation and preserve trust.','What if the buyer says the feature is essential?','What should you change in the sales process?','Clarify availability promptly and involve product or engineering for accurate options. Offer only supportable alternatives and document requirements. Acknowledge the gap rather than inventing a delivery date.']
]
};
export function roleFamilies(domain:string):Seed[]{return (families[domain]||[]).map(([title,prompt,task,q1,q2,benchmark])=>({title,prompt,facts:['Original interview exercise; state any additional assumptions explicitly.','Support your recommendation with calculations, pseudocode, a diagram or a clear decision process where useful.'],task,benchmark,followups:[q1,q2]}))}
export function expandInterviews(base:Seed[]):Seed[]{return [...base,...base.map(s=>({...s,title:`Deep dive: ${s.title}`,prompt:`${s.prompt}\nInterviewer follow-up: ${s.followups[0]}`,task:`Answer this follow-up directly: ${s.followups[0]} Connect your answer to the original situation and state what additional evidence is needed.`,benchmark:`${s.benchmark} For this follow-up, distinguish what follows from the supplied facts from what needs a new assumption. Explain the mechanism, not just the conclusion.`})),...base.map(s=>({...s,title:`Pressure test: ${s.title}`,prompt:`${s.prompt}\nInterviewer challenge: ${s.followups[1]}`,task:`Respond to the challenge: ${s.followups[1]} Explain how you would verify your reasoning and when your recommendation would change.`,benchmark:`${s.benchmark} Address the specific challenge and any limits of the original approach. A defensible answer states the revised condition, a practical check and the consequence of getting it wrong.`}))]}
