import {extraSeriesCases} from './series-scenarios';
import type {CompetitionSeed,CompetitionProfile} from './competition';
import type {Event} from './engine';
type Constraint={name:string;brief:string;review:string};
const constraints:Constraint[]=[
{name:'Evidence conflict',brief:'Two stakeholders give conflicting explanations of the main problem. Neither explanation has been independently verified.',review:'Separate verified facts from claims. Name the evidence that would distinguish the explanations, and make any interim action reversible.'},
{name:'Limited capacity',brief:'The person who would normally implement your recommendation is unavailable this week. You must identify an interim owner and a realistic handoff.',review:'Specify responsibilities and what can safely wait. Avoid assigning work to an unavailable person or assuming that a replacement has the same expertise.'},
{name:'No extra budget',brief:'No additional discretionary spending will be approved for your proposed changes this month. Existing commitments and facts in the brief remain in place.',review:'Prioritize actions within existing resources, explain opportunity costs and identify anything that must be deferred. Do not quietly invent new funding.'},
{name:'Customer confidence',brief:'An affected customer or stakeholder has lost confidence after a previous promise was missed. They want an explanation of what will be different this time.',review:'Acknowledge the concern, offer supportable commitments and define an update or verification process. A confident tone does not replace evidence.'},
{name:'Uneven impact',brief:'Your proposal may benefit one stakeholder group while creating extra work or inconvenience for another. The judge asks you to make that trade-off explicit.',review:'Identify affected groups and the mechanism of the burden. Compare an alternative, offer a practical mitigation and explain the remaining trade-off.'},
{name:'Decision tomorrow',brief:'The judge needs a defensible initial decision tomorrow. A fuller investigation can follow, but you must explain what is safe to decide now.',review:'Distinguish immediate containment or reversible action from a final commitment. Identify the highest-value missing evidence and a clear review date.'},
{name:'Success is disputed',brief:'Stakeholders disagree on what would count as success. One favors speed, another accuracy or quality, and another cost.',review:'Define measures with a baseline, owner and review cadence. Include guardrails so that optimizing one measure does not undermine the others.'}
];
const lenses=[
{name:'Explain the mechanism',task:'Explain why your recommendation should work, step by step. Apply every listed indicator or rated content requirement to the situation.'},
{name:'Compare alternatives',task:'Compare two plausible responses, including their costs or consequences, before recommending one. Apply the full indicator set.'},
{name:'Make it executable',task:'Turn your recommendation into a clear sequence with owners, dependencies and a first check. Connect that plan to the full indicator set.'},
{name:'Defend the assumption',task:'Identify the assumption most likely to change your recommendation. Explain what would happen if it were false and apply the full indicator set.'},
{name:'Communicate the decision',task:'Deliver the recommendation in role, using language appropriate to the judge. Explain difficult trade-offs while applying the full indicator set.'},
{name:'Design the check',task:'Explain how the judge could verify that your approach worked. Define a baseline, outcome measure and warning sign, while addressing the full indicator set.'},
{name:'Handle the objection',task:'Anticipate the strongest reasonable objection to your recommendation and respond to it without dismissing the concern. Address all listed indicators.'}
];
export function expandCompetition(e:Event,base:CompetitionSeed[],p:CompetitionProfile):CompetitionSeed[]{
 if(e.id==='fbla-impromptu-speaking'){const topics=['Can a small failure make a stronger leader?','When does convenience become a bad trade-off?','What makes a promise credible?','Should a business prioritize growth or resilience?','How should a team learn from disagreement?','What does responsible innovation look like?','When is patience a competitive advantage?','How can a leader earn trust after a mistake?','What is the value of asking better questions?','How should success be measured beyond profit?','When should a tradition be challenged?','Can competition and cooperation coexist?','What makes feedback useful?','How can technology help people feel included?','Why does a community need small businesses?','When should a leader say no?','What is the difference between confidence and certainty?','How can a team make decisions with incomplete information?','What responsibility comes with influence?','How can preparation support creativity?','What makes work meaningful?','How should people balance ambition and wellbeing?'];return [...base,...topics.map((topic,i)=>({...base[0],title:`Impromptu speech: practice ${i+3}`,prompt:topic}))]}
 const additions=e.path==='deca'?extraSeriesCases(e.code,base[0]):[];
 const roleplay=p.format==='Role Play'||base[0]?.kind==='roleplay';
 const count=roleplay?100:24;
 const core=[...base,...additions];const added=Array.from({length:count-core.length},(_,i)=>{const original=core[i%core.length],constraint=constraints[Math.floor(i/(7*core.length))%7],lens=lenses[Math.floor(i/core.length)%7];const focus=p.indicators.length?p.indicators[i%p.indicators.length].label:null;
 const prepared=original.kind==='prepared';
 const brief=prepared?`Preparation challenge: ${constraint.brief} This is a coaching constraint for your rehearsal; the official topic, eligibility, materials and submission rules still govern your real entry.`:constraint.brief;
 return {...original,title:`${String(i+core.length+1).padStart(3,'0')} · ${constraint.name} / ${lens.name}`,round:roleplay?'Scenario variation':'Preparation variation',prompt:`${original.prompt}\n\nAdditional rehearsal constraint: ${brief}\nJudge emphasis: ${lens.task}`,facts:[...original.facts,focus?`Give particular attention to: ${focus} The full listed set is still assessed.`:`Practice focus: ${lens.name.toLowerCase()}.`],task:`${original.task}\n${lens.task}`,benchmark:`Base-case reasoning: ${original.benchmark}\nAdaptation required in this variation: ${constraint.review} The base approach must be revised where the added constraint makes it impractical. ${focus?`Explain and apply “${focus}” in context; do not simply recite it.`:''}`,followups:[`How does the ${constraint.name.toLowerCase()} constraint change your first action?`,original.followups[i%2]]};});
 return [...base,...additions,...added];
}
