'use client';
import {wordCount} from './library-utils';
import InterviewAssessment from './interview-assessment';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Clock3,Pause,Play,RotateCcw,Download,Upload,CheckCircle2,CircleHelp,ChartNoAxesCombined,MessageSquareText,ChevronRight,Check,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import VisualBuilder,{downloadFile,getSeries} from '../visual-builder';
import type {Visual} from '../workbench-types';
import {review,levels,levelPrompt,formatNote,type Event,type PracticeCase,type Work} from './engine';
type Saved=Work&{version:1;caseId:string;reviewId?:string;level:number;elapsed:number;visuals:Visual[]};
const fresh=(c:PracticeCase):Saved=>({version:1,caseId:c.id,response:'',results:c.numbers.map(()=>''),followups:['',''],level:0,elapsed:0,visuals:[]});
function validate(value:unknown,c:PracticeCase):Saved{const v=value as Saved;if(!v||v.version!==1||v.caseId!==c.id||typeof v.response!=='string'||v.response.length>24000||!Number.isInteger(v.level)||v.level<0||v.level>2||!Number.isFinite(v.elapsed)||v.elapsed<0||v.elapsed>604800||!Array.isArray(v.results)||v.results.length!==c.numbers.length||v.results.some(x=>typeof x!=='string'||x.length>100)||!Array.isArray(v.followups)||v.followups.length!==2||v.followups.some(x=>typeof x!=='string'||x.length>6000)||!Array.isArray(v.visuals)||v.visuals.length>4)throw Error('This is not a valid draft for this case.');for(const a of v.visuals){if(!a||typeof a.id!=='string'||!['bar','line','area'].includes(a.type)||typeof a.title!=='string'||a.title.length>120||typeof a.unit!=='string'||a.unit.length>60||typeof a.caption!=='string'||a.caption.length>1200||!Array.isArray(a.series)||!a.series.length||a.series.length>10||a.series.some(s=>!s||typeof s.label!=='string'||s.label.length>60||typeof s.formula!=='string'||s.formula.length>500))throw Error('The draft contains an invalid exhibit.')}if(new Set(v.visuals.map(x=>x.id)).size!==v.visuals.length)throw Error('Duplicate exhibit identifiers.');return v}
export default function Practice({event,c,onBack,onReview,onNext}:{event:Event;c:PracticeCase;onBack:()=>void;onReview:(score:number)=>void;onNext:()=>void}){
 const[d,setD]=useState<Saved>(()=>fresh(c)),[loaded,setLoaded]=useState(false),[running,setRunning]=useState(false),[tab,setTab]=useState('answer'),[snapshot,setSnapshot]=useState<Saved|null>(null),[message,setMessage]=useState(''),[storage,setStorage]=useState(true);
 const input=useRef<HTMLInputElement>(null);const key=`casecraft-practice-draft:${c.id}`;
 useEffect(()=>{try{const raw=sessionStorage.getItem(key);if(raw)setD(validate(JSON.parse(raw),c));const savedReview=sessionStorage.getItem(key+':review');if(savedReview){setSnapshot({...validate(JSON.parse(savedReview),c),reviewId:JSON.parse(savedReview).reviewId||crypto.randomUUID()});setMessage('Your draft and last completed review are restored. Review again after revising your answer.')}}catch{setMessage('A previous draft could not be restored. You can import an exported draft.')}setLoaded(true)},[key,c]);
 useEffect(()=>{if(!loaded)return;try{sessionStorage.setItem(key,JSON.stringify(d));setStorage(true)}catch{setStorage(false)}},[d,key,loaded]);
 useEffect(()=>{if(!loaded)return;try{if(snapshot)sessionStorage.setItem(key+':review',JSON.stringify(snapshot));else sessionStorage.removeItem(key+':review')}catch{setStorage(false)}},[snapshot,key,loaded]);
 useEffect(()=>{if(!running)return;const started=Date.now(),base=d.elapsed;const timer=setInterval(()=>setD(v=>({...v,elapsed:Math.min(604800,base+Math.floor((Date.now()-started)/1000))})),1000);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{const n=navigator as Navigator&{modelContext?:{registerTool:(t:unknown)=>void;unregisterTool:(s:string)=>void}};if(!n.modelContext)return;const name='read_practice_case';n.modelContext.registerTool({name,description:'Read the current Casecraft practice prompt and the learner’s current draft. Does not submit or modify work.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify({event:event.name,title:c.title,prompt:c.prompt,facts:c.facts,task:c.task,draft:d})}]})});return()=>n.modelContext?.unregisterTool(name)},[c,d,event]);
 const patch=(p:Partial<Saved>)=>setD(v=>({...v,...p}));const report=snapshot?review(c,snapshot,snapshot.level):null;
 function submit(){if(!d.response.trim()){setMessage('Write your answer before requesting a practice check.');return}const invalid=d.visuals.some(v=>getSeries(v,[],[]).some(s=>s.error));if(invalid){setMessage('Fix or remove invalid chart values before reviewing.');return}const copy={...structuredClone(d),reviewId:crypto.randomUUID()};setSnapshot(copy);setRunning(false);setTab('review');setMessage('')}
 function exportDraft(){downloadFile(`casecraft-${event.id}-draft.json`,JSON.stringify(d,null,2),'application/json');setMessage('Draft exported. Keep the downloaded file to restore your work later.')}
 async function importDraft(file?:File){if(!file)return;try{if(file.size>100000)throw Error('Draft file is too large.');const next=validate(JSON.parse(await file.text()),c);setD(next);setSnapshot(null);setTab('answer');setRunning(false);setMessage('Draft imported.')}catch(e){setMessage(e instanceof Error?e.message:'Draft could not be imported.')}if(input.current)input.current.value=''}
 function exportReview(){if(!snapshot||!report)return;const text=`# ${c.title}\n${event.name} · ${levels[snapshot.level]}\n\nNumerical checks: ${report.numericSummary.passed}/${report.numericSummary.total}. No automatic written-answer grade is assigned.\n\n## Prompt\n${c.prompt}\n${c.facts.map(f=>'- '+f).join('\n')}\n\n${c.task}\n\n## Your answer\n${snapshot.response}\n\n## Numerical checks\n${report.numeric.map(n=>`${n.label}: submitted ${n.submitted??'blank'}; expected ${n.answer} ${n.unit}; ${n.correct?'matched':'revise'}`).join('\n')}\n\n## Follow-up answers\n${snapshot.followups.map((a,i)=>`${c.followups[i]}\n${a||'(not answered)'}`).join('\n\n')}\n\n## Reasoning coverage\n${report.evidence.map(e=>`${e.label}: ${e.detected?'topic detected, correctness unverified':'not detected'}\n${e.detected?e.excerpt:e.next}`).join('\n\n')}\n\n## Worked reasoning and comparison\n${c.benchmark}\n\n## Next steps\n1. Correct any numerical mismatches.\n2. Compare the logic of your answer with the worked reasoning; identifying a topic does not prove it was used correctly.\n3. Rehearse both follow-ups out loud and revise your answer.\n\n## Exhibits\n${snapshot.visuals.map(v=>`${v.title} (${v.unit})\n${getSeries(v,[],[]).map(s=>s.name+': '+s.value).join('\n')}\n${v.caption}`).join('\n\n')}\n\nOfficial guidance: ${event.source}\n`;downloadFile(`casecraft-${event.id}-debrief.md`,text,'text/markdown')}
 return <main className="practice-main"><div className="session-top"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/> {event.code||event.name}</button><span className="free-badge"><span className="live-dot"/> Free practice review</span></div><div className="session-heading"><div><div className="eyebrow">{event.name} / PRACTICE {String(c.index+1).padStart(2,'0')}</div><h1>{c.title}</h1></div><div className="timer-control"><Clock3 size={17}/><span aria-label="Elapsed practice time">{Math.floor(d.elapsed/60).toString().padStart(2,'0')}:{(d.elapsed%60).toString().padStart(2,'0')}</span><button className="icon-button" title={running?'Pause timer':'Start timer'} aria-label={running?'Pause timer':'Start timer'} onClick={()=>setRunning(!running)}>{running?<Pause size={15}/>:<Play size={15}/>}</button></div></div>
 <div className="session-toolbar"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList aria-label="Practice workspace" className="workspace-tabs"><TabsTrigger value="answer">Your answer</TabsTrigger><TabsTrigger value="review" disabled={!snapshot}>Debrief {snapshot&&<Check size={14}/>}</TabsTrigger></TabsList></Tabs><div className="draft-actions"><button className="text-button" onClick={exportDraft}><Download size={14}/> Save draft</button><button className="text-button" onClick={()=>input.current?.click()}><Upload size={14}/> Import</button><input type="file" accept=".json,application/json" ref={input} hidden onChange={e=>importDraft(e.target.files?.[0])}/></div></div>
 {message&&<p className="practice-notice" role="status">{message}</p>}
 {tab==='answer'?<><div className="practice-columns"><section className="case-brief"><span className="eyebrow">THE SCENARIO</span><p className="case-situation">{c.prompt}</p><h3>What you know</h3><ul className="fact-list">{c.facts.map((f,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span>{f}</li>)}</ul><div className="your-task"><span className="eyebrow">YOUR TASK</span><p>{c.task}</p></div><details className="practice-details"><summary><CircleHelp size={15}/> How to approach it</summary><p>Start with your conclusion or approach. Use the facts, show calculations where relevant, and explain assumptions. Address a trade-off, limitation or edge case. Finish with a check or next step.</p><p>{formatNote(event)}</p><a href={event.source} target="_blank" rel="noreferrer">Read official guidance ↗</a></details><fieldset className="difficulty-field"><legend>Practice setting</legend><RadioGroup className="practice-settings" value={String(d.level)} onValueChange={v=>{const next=Number(v);if(Number.isInteger(next)&&next>=0&&next<=2)patch({level:next})}} aria-label="Practice setting">{levels.map((l,i)=><label key={l} className={d.level===i?'setting-option selected':'setting-option'}><RadioGroupItem value={String(i)}/><span><b>{l}</b><small>{['Core answer only','Core answer + one follow-up','Core answer + both follow-ups'][i]}</small></span></label>)}</RadioGroup><p>{levelPrompt(d.level,c)}</p><small>No official timing is simulated. The stopwatch is optional.</small></fieldset></section>
 <section className="answer-panel"><div className="answer-label"><label htmlFor="case-answer">Make your case.</label><span>Your words. Your reasoning.</span></div><textarea id="case-answer" className="main-answer" value={d.response} maxLength={24000} onChange={e=>patch({response:e.target.value})} placeholder={"My answer is…\n\nHere’s the reasoning and the evidence…\n\nThe main limitation is…\n\nI would check…"}/><div className="answer-meta"><span>{storage?'Draft and last review kept in this tab. Export a backup.':'Browser storage unavailable. Export your draft.'}</span><span>{wordCount(d.response).toLocaleString()} words · {d.response.length.toLocaleString()} / 24,000</span></div>
 {c.numbers.length>0&&<div className="result-fields"><h3>Check your key results</h3><p>Enter numbers here so the free reviewer can verify them. Explain the workings in your answer.</p>{c.numbers.map((n,i)=><label key={n.label}>{n.label}<div><input inputMode="text" value={d.results[i]||''} maxLength={100} onChange={e=>patch({results:d.results.map((v,j)=>j===i?e.target.value:v)})} placeholder="Your result"/><span>{n.unit}</span></div></label>)}</div>}
 {d.level>0&&<section className="followup-fields"><div className="eyebrow">THE FOLLOW-UP</div>{c.followups.slice(0,d.level===1?1:2).map((q,i)=><label key={q}><span><MessageSquareText size={16}/> {q}</span><textarea rows={4} value={d.followups[i]} maxLength={6000} onChange={e=>patch({followups:d.followups.map((v,j)=>i===j?e.target.value:v)})} placeholder="Defend or adapt your answer…"/></label>)}</section>}
 </section></div><details className="optional-visuals"><summary><ChartNoAxesCombined size={20}/><div><b>Add a visual</b><span>Optional · charts for evidence, comparisons, or a simple model</span></div><ChevronRight size={18}/></summary><div className="optional-visual-body"><VisualBuilder visuals={d.visuals} setVisuals={v=>patch({visuals:v})} rows={[]} data={[]} manual/></div></details><div className="submit-strip"><div><b>Ready for a useful second look?</b><p>Free numerical checks, topic coverage, worked reasoning, and next steps.</p></div><button className="primary" disabled={!loaded||!d.response.trim()} onClick={submit}>Review my answer <ArrowRight size={17}/></button></div><p className="review-explainer"><Info size={14}/> Free review checks numbers and whether key topics appear. It cannot verify every written claim, judge delivery, or execute code. No AI call or payment is required.</p></>:report&&snapshot?<div className="debrief">
 <section className="debrief-hero"><div><span className="eyebrow">VERIFIED NUMERICAL CHECKS</span><h2>{report.numericSummary.total?`${report.numericSummary.passed} of ${report.numericSummary.total} numerical answers match`:'Written answer ready for review'}</h2><p>Keywords and completed text fields do not earn marks. These checks verify entered numbers only; use the written review below for a reasoning grade.</p></div></section>
 <InterviewAssessment key={snapshot.reviewId} event={event} c={c} work={snapshot} onReview={onReview}/>
 <div className="debrief-actions"><button className="primary" onClick={()=>setTab('answer')}><RotateCcw size={16}/> Revise your answer</button><button className="secondary-button" onClick={exportReview}><Download size={16}/> Export debrief</button><button className="text-button" onClick={onNext}>Next practice <ArrowRight size={16}/></button></div>
 {report.numeric.length>0&&<section className="debrief-section"><span className="eyebrow">01 / VERIFIED RESULTS</span><h2>Do the numbers hold up?</h2><div className="number-results">{report.numeric.map(n=><article key={n.label} className={n.correct?'passed':'needs-work'}><div>{n.correct?<CheckCircle2 size={20}/>:<CircleHelp size={20}/>}<h3>{n.label}</h3></div><p>Your result: <b>{n.submitted??'Not provided'} {n.submitted!==null?n.unit:''}</b></p><p>Expected: <b>{n.answer.toLocaleString(undefined,{maximumFractionDigits:6})} {n.unit}</b></p><span>{n.correct?'Matches within the stated rounding tolerance.':'Rework this result using the explanation below. A mismatch can change the recommendation.'}</span></article>)}</div></section>}
 <section className="debrief-section"><span className="eyebrow">{report.numeric.length?'02':'01'} / YOUR REASONING</span><h2>What appeared—and what needs a closer look.</h2><p className="section-description">These are coverage signals, not claims that your reasoning is correct.</p><div className="evidence-grid">{report.evidence.map(e=><article key={e.label}><span className={'signal '+(e.detected?'detected':'missing')}>{e.detected?'Topic detected':'Not detected'}</span><h3>{e.label}</h3>{e.detected?<><blockquote>“{e.excerpt}”</blockquote><p>Check whether this statement is supported by the facts and whether it actually changes your answer.</p></>:<p>{e.next} If you already addressed this with different wording, use the worked reasoning to verify it.</p>}</article>)}</div></section>
 <section className="worked-reasoning"><div><span className="eyebrow">THE COACH’S NOTES</span><h2>Compare the logic, not just the conclusion.</h2></div><p>{c.benchmark}</p><div className="reasoning-questions"><span>Where does your answer make the same connection?</span><span>Where does it rely on an unsupported assumption?</span><span>Could a different answer work under different conditions?</span></div><small>This is a reference approach, not the only acceptable solution.</small></section>
 <section className="debrief-section"><span className="eyebrow">YOUR NEXT REPS</span><h2>Turn feedback into a stronger attempt.</h2><ol className="next-steps">{report.numeric.some(n=>!n.correct)&&<li><b>Repair the calculation.</b><p>Recompute {report.numeric.filter(n=>!n.correct).map(n=>n.label.toLowerCase()).join(' and ')}. Then check whether your recommendation still follows.</p></li>}{report.evidence.filter(e=>!e.detected).slice(0,2).map(e=><li key={e.label}><b>Make {e.label.toLowerCase()} explicit.</b><p>{e.next}</p></li>)}<li><b>Defend the answer.</b><p>{c.followups[0]}</p></li><li><b>Change one assumption.</b><p>{c.followups[1]}</p></li><li><b>Rehearse with a person.</b><p>Explain your answer out loud. Ask them to challenge the reasoning and give feedback on delivery. Use the official rating sheet where relevant.</p></li></ol></section>
 {snapshot.visuals.length>0&&<div className="practice-notice">Your {snapshot.visuals.length} exhibit(s) are included in the exported debrief as data and captions. The free score does not judge their visual quality or whether they prove your claim.</div>}
 <details className="submitted-answer"><summary>View the answer behind this review</summary><h3>Your response</h3><p>{snapshot.response}</p>{snapshot.followups.map((a,i)=>a?<div key={i}><h3>{c.followups[i]}</h3><p>{a}</p></div>:null)}</details>
 </div>:null}</main>
}
