import type {CompetitionSeed} from './competition';
// Additional original situations use the same source-selected indicator set, not invented PI codes.
type Scenario=[string,string,string[],string];
const scenarios:Record<string,Scenario[]>={
ACT:[
['The prepaid service contract','A repair-business owner wants to understand why a prepaid maintenance contract cannot all be reported as revenue today.',['A customer paid $12,000 for 12 equal monthly services beginning this month; one service has been completed','The business also paid $2,400 for 12 months of insurance beginning this month','No other transactions are included in this exercise'],'Recognize $1,000 service revenue and retain $11,000 as a contract liability. Record $200 insurance expense and $2,200 prepaid insurance. Trace cash, adjustments and equity through the accounting equation; organize supporting records and explain the cycle clearly.'],
['Equipment bought partly on credit','The owner of a workshop confuses an equipment purchase with an immediate operating expense. Explain the transactions and the month-end process.',['Equipment costing $20,000 is acquired using $5,000 cash and $15,000 vendor financing','The equipment is available for use; estimated life is five years and residual value is zero','Use straight-line depreciation and assume one full month of use'],'The purchase adds $20,000 equipment, reduces cash $5,000 and adds a $15,000 liability. Monthly depreciation is about $333.33, reducing net assets and equity; it does not repay the debt. Separate acquisition, financing, adjustment and reporting steps and state rounding.']
],
AAM:[
['The store-transfer mismatch','An apparel store receives stock from a sister location before a weekend sale. The system count and actual delivery disagree.',['The transfer record lists 40 dresses; 36 arrive','Four arriving dresses have broken fasteners','Two customers want exchanges under a posted 30-day policy; replacement sizes have not been verified'],'Reconcile the transfer and condition before releasing stock for sale. Quarantine damaged items and investigate the four missing units separately. Explain exchange options without promising unverified sizes; document the handoff between stores.'],
['A return with a safety concern','An apparel customer returns a jacket after reporting a sharp exposed fastener. Similar jackets remain on the sales floor.',['The purchase is within the store’s return period','The report is not yet confirmed as a batch-wide defect','A new shipment from the same supplier arrives today'],'Handle the customer under the stated policy and inspect the reported issue. Isolate potentially affected stock pending an appropriate review, record lot and shipment details, and escalate to the responsible manager or supplier. Do not claim all items are safe or defective without evidence.']
],
ASM:[
['Promote a mobile service pilot','An auto-service business is piloting scheduled mobile maintenance for employees at a local business park.',['Promotion budget is $1,800','Each completed service contributes $60 before promotion costs','The pilot can complete at most 40 incremental services','Customers must authorize the written estimate before work'],'Break-even is 30 incremental services, leaving a narrow capacity margin. Choose relevant employer and customer communication, distinguish promotional channels, explain convenience and authorized estimates, and measure incremental bookings and satisfaction. Do not promise capacity beyond 40.'],
['The lapsed-customer campaign','An auto-service manager wants former customers to return after introducing a clearer estimate and approval process.',['Research suggests surprise bills damaged trust','Staff now explain the estimate and request approval for additional work','The manager proposes a discount before checking why each customer left'],'Build promotion around a credible service change and appropriate customer outreach. Segment the audience, explain the advantage with evidence and align staff behavior with the message. Test incremental return visits and avoid implying that a discount resolves a trust problem alone.']
],
BFS:[
['Fast growth, slow collections','A subscription-services company has enough accounting revenue but faces a near-term cash squeeze.',['Opening cash is $22,000','Payroll and supplier payments total $39,000 this week','A verified $8,000 customer receipt is due before those payments','Other receivables are disputed or not due yet'],'The verified shortfall is $9,000. Build a dated cash forecast, distinguish confirmed from uncertain collections and compare practical financing or negotiated-payment options. Explain receivables timing and cash-management responsibilities without treating disputed invoices as available cash.'],
['Inventory before the seasonal rush','A retailer must fund seasonal inventory before customer cash arrives. The owner asks whether a profitable forecast eliminates the need for financing.',['Inventory suppliers require payment in two weeks','Most customer sales occur six weeks later','Sales estimates have not been validated against current demand'],'Map the cash-conversion gap and test demand and collection assumptions. Stage orders or negotiate terms where feasible, compare financing cost and downside liquidity, and organize the forecast for the owner. Profitability and funding timing are distinct questions.']
],
BSM:[
['The compliance-support package','A business-services firm wants to add document tracking and onboarding support for small employers.',['Customers want a single contact and clear scope','The team can add one pilot service without hiring','A rival advertises an unlimited package','The firm does not provide legal advice'],'Generate feasible services around customer needs, choose a coherent mix and differentiate through scope clarity and continuity. Avoid implying legal expertise. Pilot the addition with capacity, margin and repeat-client checks before expanding.'],
['Too many service choices','A consulting-support firm offers 18 loosely described services. Prospects struggle to choose and sales cycles are lengthening.',['Existing clients value the named account coordinator','Demand differs between solo businesses and growing teams','The team wants to preserve profitable specialist work'],'Organize a few need-based packages while retaining scoped specialist options. Explain the mix and competitive value rather than merely reducing the menu. Gather prospect feedback and build a structured follow-up process to develop clients.']
],
ENT:[
['Choose the first delivery customer','A start-up can offer scheduled local deliveries to either small retailers or individual households.',['Retailers prioritize predictable collection times','Households prioritize evening flexibility','One vehicle is available and only one segment can be served initially'],'Choose a target market using needs and operating feasibility. Design the service mix around that segment and articulate a distinctive promise supported by the vehicle constraint. Test willingness to use the service and avoid promising incompatible schedules.'],
['A tutoring-service position','A founder must position a new tutoring service in a crowded local market.',['One segment wants exam preparation; another wants ongoing study support','Only two qualified tutors are available','The founder cannot guarantee grades'],'Select the initial segment and service mix, explain how service delivery supports positioning and define a credible value proposition. Avoid guaranteed outcomes; validate demand and schedule capacity before broadening the offer.']
],
FMS:[
['Explain a recipe change','A food retailer changes a popular product’s recipe and receives conflicting questions from staff and customers.',['The ingredient list is verified but some advertising still shows the old recipe','Front-line staff have not received a briefing','Customers care about taste, ingredient transparency and value'],'Coordinate accurate internal and customer messages, correct stale material and explain the product’s meaning and value without unsupported health claims. Build trust through listening, consistent service and respectful staff collaboration.'],
['Local-supplier misunderstanding','A food market promotes a local supplier but customers assume every ingredient is locally sourced.',['The supplier is local; some inputs come from elsewhere','Staff give inconsistent explanations','The retailer wants to preserve the supplier relationship'],'Clarify the claim precisely, align employee information and update misleading messaging. Communicate respectfully with the supplier and customers, explain the actual product value and check understanding rather than defending an ambiguous slogan.']
],
HLM:[
['Fill the quiet Sunday','A hotel wants to increase Sunday room demand without disrupting regular guests.',['Sunday occupancy is lower than other days','The hotel has a meeting lounge but no full-service restaurant','Nearby visitors often arrive for Monday appointments'],'Develop a targeted room-sales opportunity using supportable amenities and appropriate hospitality promotion channels. Align the guest-service promise with actual operations, measure incremental room contribution and avoid advertising unavailable food service.'],
['A package after the event','A hotel near a performance venue wants guests to stay overnight instead of travelling home.',['The hotel has limited late check-in staffing','The venue has not agreed to a partnership','Guests ask about transport and accessible room availability'],'Identify the target audience and a feasible lodging offer, choose channels and confirm any partnership before using its name. Address arrival and service expectations, verify transport and accessibility information, and measure bookings without overstating availability.']
],
HRM:[
['Who should lead the new shift?','Two employees want a shift-lead position, and each has different strengths.',['One has strong technical skills; the other is better at resolving team disagreements','No written selection criteria have been shared','The successful candidate will coach new staff'],'Determine the skills required, gather relevant evidence and feedback, and use a transparent selection process. Recognize both employees fairly, explain development paths and motivate the team without rewarding visibility over job-relevant competence.'],
['Recognition that divides the team','A manager’s monthly award consistently favors visible front-desk work while back-office staff feel ignored.',['No award criteria are published','Customer service depends on both groups','The manager has not collected staff feedback'],'Gather information from both roles and assess the skills and contributions that support results. Create fair, explainable recognition criteria and development opportunities. Use feedback to improve motivation rather than assuming dissatisfaction is disloyalty.']
],
MCS:[
['Launch through customer stories','A reusable-bag brand wants customers to share genuine uses of its product during a launch.',['The team can produce a small set of visual examples','Customers may upload images containing other people','The brand promises durability but has limited long-term evidence'],'Connect marketing to customer and economic value, encourage authentic word of mouth and develop useful visual content. Monitor community material, obtain appropriate permissions and avoid durability claims that exceed evidence. Keep the corporate brand consistent.'],
['A viral post with the wrong promise','A short customer video goes viral but claims a product feature the brand does not offer.',['The brand is preparing a wider campaign','Employees want to repost the video immediately','The customer is enthusiastic rather than intentionally misleading'],'Correct the misunderstanding respectfully before amplifying it. Use accurate visual content and monitor user-generated claims while preserving authentic advocacy. Explain the brand’s real value and the broader cost of misleading marketing.']
],
QSRM:[
['Name the new menu item','A quick-service restaurant is launching a plant-based bowl and wants a clear menu description and promotion.',['Ingredients are verified','The preparation area is shared with other foods','The team wants to use a claim of allergen-free preparation without supporting controls'],'Develop a product identity and useful description based on verified facts. Avoid unsupported allergen claims. Select suitable hospitality promotional channels and explain the offer’s actual value while aligning staff explanations with the menu.'],
['A breakfast offer nobody understands','A quick-service café has added a breakfast bundle but customers misunderstand what is included.',['The sign shows three products but the price includes only two','The offer is available until 10 a.m.','Staff frequently need to correct orders'],'Clarify the item identity, description, price and time limit across menu and promotions. Explain the bundle’s value without misleading imagery, select relevant channels and check whether revised communication reduces confusion.']
],
RFSM:[
['The missed anniversary booking','A restaurant cannot find a guest’s anniversary reservation and the guest is upset in a crowded entrance.',['The guest has a confirmation email','No suitable table is immediately available','The employee cannot authorize unlimited compensation'],'Listen, acknowledge the experience and verify the record while offering realistic options within authority. Protect dignity and avoid a public argument. Follow up to rebuild the relationship and address the process behind the failure.'],
['A regular guest feels excluded','A restaurant changes its ordering process and a regular guest struggles to use it.',['Staff are encouraged to direct everyone to a self-service kiosk','The guest asks for help rather than a discount','A manual ordering option still exists'],'Use a service-first interaction and offer the available assistance without blaming the guest. Explain the process clearly, preserve choice and collect feedback about barriers. A positive experience and long-term relationship matter beyond transaction speed.']
],
RMS:[
['A store event with limited floor space','A retailer plans a product-demonstration event but the proposed display obstructs customer movement.',['The event must take place during regular opening hours','Customers want to compare products before buying','Staff have not been assigned event roles'],'Plan the event around safe, usable circulation and buying needs. Prepare displays and staff responsibilities, support comparison and explain how service builds the selling relationship. Measure useful engagement and sales outcomes without blocking regular customers.'],
['Promote a repair-and-reuse weekend','A retailer is hosting a weekend demonstration of product care and repair.',['Visitors include existing owners and potential buyers','Demonstrators can serve only a limited number of people at once','The store wants a display that explains long-term value'],'Plan an accessible event flow and display, prepare staff and manage demand. Relate buying motives to durability and support without guaranteeing every repair. Use helpful service and follow-up to develop customer relationships.']
],
SEM:[
['Sell a corporate game-night package','A sports organization pitches a group ticket package to a local employer.',['The buyer wants staff participation rather than executive hospitality','Employees work different shifts','The seller has flexible dates but limited premium seats'],'Use discovery to understand buying motives, follow the selling process and match a feasible offer to participation needs. Connect marketing strategy to the target buyer and track qualified interest, attendance and follow-up rather than only impressions.'],
['An arts venue wants repeat groups','An entertainment venue wants community organizations to return for more than one performance.',['Past groups liked the events but found coordination difficult','Organizers need predictable communication and clear booking deadlines','Discounting every ticket would reduce contribution'],'Identify the organizer’s buying needs and design a selling process that reduces coordination friction. Develop targeted marketing and tracking through inquiry, booking and repeat attendance. Explain service and scheduling value before assuming a discount is necessary.']
]
};
export function extraSeriesCases(code:string,base:CompetitionSeed):CompetitionSeed[]{return (scenarios[code]||[]).map(([title,prompt,facts,benchmark])=>({...base,title,prompt,facts,benchmark,round:'Core rehearsal',task:'Respond in your stated role to the judge. Apply every performance indicator listed below, explain your recommendation and make its assumptions and consequences clear.',followups:['Which evidence or fact most strongly supports your recommendation?','What could make this approach fail, and how would you detect that early?']}))}
