'use client';

import {useEffect, useRef, useState} from 'react';
import {ArrowLeft, ArrowRight, Check, GraduationCap, BriefcaseBusiness, BookOpen} from 'lucide-react';
import {Dialog, DialogContent, DialogTitle, DialogDescription} from '@/components/ui/dialog';

export type GuidePath = 'competition' | 'career';
type Step = {title: string; body: string; actions: string[]; example: string; tip: string};
const guides: Record<GuidePath, Step[]> = {
  competition: [
    {title: 'Find your event', body: 'Start in Competition Hall. Choose DECA or FBLA, then find the event you actually compete in.', actions: ['Search by event name, code, or skill. Use sector and format filters to narrow the list; Reset filters brings it back.', 'Bookmark an event with its bookmark icon. Saved events shows your shortlist on this device.', 'Open the event and check its official source, season, participants, and format. Local qualification rules can differ.'], example: 'DECA → search “ACT” → Accounting Applications Series → choose a core rehearsal.', tip: 'New to the event? Start with a core case before trying a pressure round or rehearsal variation.'},
    {title: 'Read the brief with a purpose', body: 'Identify who you are, who the judge is, and the decision they need from you.', actions: ['Read the facts and task before writing. Separate known facts from assumptions.', 'For DECA role-plays, apply every listed performance indicator. The selected indicators belong to this rehearsal, not every possible case in the series.', 'For FBLA and prepared events, use the rated requirements and Official scorecard. Open Rules and source notes for materials and timing.'], example: 'Role: junior accountant. Audience: business owner. Decision: which transactions belong in this month’s accounts?', tip: 'Write a one-sentence version of the task. If you cannot state the decision, reread the brief.'},
    {title: 'Choose how to rehearse', body: 'Use Guided practice while learning. Switch to Timed rehearsal when you are ready for the supported role-play format.', actions: ['Begin preparation starts the prep phase. Meet the judge moves to the presentation phase and reveals the judge questions.', 'Timed rehearsal uses the event’s displayed prep and presentation windows. Guided practice lets you work at your own pace.', 'Prepared and knowledge formats do not use the same role-play timer. Follow their official instructions; a written practice cannot replace the real deliverable or exam.'], example: 'During preparation: identify the issue → outline each indicator → check your recommendation. During presentation: explain it in role.', tip: 'Budget time for a conclusion and judge questions. A complete, clear answer is more useful than a long introduction.'},
    {title: 'Build a solution that holds up', body: 'Explain a decision and its consequences. Naming a concept is not the same as applying it.', actions: ['Lead with your recommendation, then connect it to the case facts and each relevant criterion.', 'Show calculations, state assumptions, compare an alternative, and explain the main risk.', 'Finish with who acts, what happens first, and how success will be checked. Answer the judge’s follow-ups.'], example: '“Record the $1,500 advance as a liability because the repair is next month. Counting it as earned revenue would overstate this month’s result. Reconcile deposits before sending the lender’s report.”', tip: 'A useful outline: decision → evidence → mechanism → alternative and risk → next action. Use it as a structure, not a script.'},
    {title: 'Make a visual earn its place', body: 'The optional visual workspace is a learning aid. Real competition materials rules still apply.', actions: ['In Guided practice, expand Optional visual workspace and create an exhibit. Choose bar, line, or area; add a title and axis units.', 'Enter labeled series with numbers or arithmetic, such as 9000+2000. Add or remove series and exhibits as needed; invalid values must be corrected before submitting.', 'Write the takeaway. View chart data to verify the values, or download an SVG for your own work.'], example: 'Use a bar chart to compare earned revenue and customer advances. Caption: “Cash received is not the same as revenue earned.”', tip: 'Bar charts compare categories. Lines and areas suggest an ordered sequence. A chart should help explain a decision, not fill space.'},
    {title: 'Use the right scorecard', body: 'Open Official scorecard to see the criteria and point bands. Finish & debrief captures the answer you want reviewed.', actions: ['Select the scoring component you are assessing. A written report, presentation, and exam are separate components.', 'Compare your response with the reference reasoning and identify evidence for each criterion.', 'For adviser, peer, or self-review, enter a mark with evidence and a specific next step. Leave unobserved delivery or missing artifacts unassessed.'], example: 'A 190-point pre-judged asset and a 110-point presentation are two scorecards. Do not treat one as the other or invent marks for work that was not observed.', tip: 'A partial assessment is not a complete competition score. Use the linked official rating sheet to interpret the point bands.'},
    {title: 'Get written feedback and revise', body: 'You can also use the copy-and-import review flow. Casecraft does not automatically send your work to an AI service.', actions: ['After submitting, choose the scorecard and Copy review prompt. Paste it into ChatGPT yourself.', 'Paste the returned JSON into Paste a ChatGPT rubric review, then Validate & import review. Casecraft checks the case, submitted attempt, criteria, and score limits.', 'Read the evidence and next steps critically. Return to your response, fix the biggest gap, and submit again. A changed submission needs a fresh review prompt.'], example: 'Instead of “be more detailed,” act on “show how the correction affects the accounting equation, then explain why the lender needs the corrected result.”', tip: 'AI feedback can be wrong. Check important claims against the source material or ask an adviser. Do not paste private information you do not want to share.'},
    {title: 'Keep your work and make the next rep count', body: 'End each attempt with one improvement you can use in the next case.', actions: ['Save exports a draft JSON file. Import it while viewing the same practice to restore that work; keep a backup before replacing a draft.', 'Export debrief to keep feedback. Bookmarks stay on the device; drafts, reviews, and recent history live in the browser tab, not a cloud account.', 'Continue practice resumes your last case in the tab. Next rehearsal opens another case. Revisit the guide anytime from How to practice.'], example: 'Before moving on: “In my next answer, I will explain the consequence of every calculation instead of only giving the number.”', tip: 'For an efficient learning session: one case, one evidence-based review, one revision. Use official timing only when deliberately rehearsing that format.'},
  ],
  career: [
    {title: 'Choose the role and the skill', body: 'Start in Career Launchpad and choose the role you are preparing for.', actions: ['Search the role catalog and bookmark roles you want to revisit. Saved roles filters your shortlist.', 'Open a role, search its practice topics, and start with a core problem. Show more practices reveals the rest of the library.', 'Read the linked employer guidance to understand the interview process. These are original exercises, not reported interview questions.'], example: 'Investment Banking → Walk me through depreciation. Later, try its deep dive and pressure test.', tip: 'Choose a skill you need to improve, rather than repeating only questions you already know.'},
    {title: 'Set a useful challenge', body: 'Read the scenario, facts, and assigned task. Then choose the amount of follow-up practice.', actions: ['Foundation covers the core response. Challenge adds one follow-up. Stretch adds both.', 'How to approach it gives a starting structure. Keep your answer specific to the task rather than following a memorized template.', 'The optional stopwatch can start and pause. It measures practice time; it does not simulate official employer timing.'], example: 'Start at Foundation to explain the three statements. Move to Stretch when you can defend the assumptions as well.', tip: 'Increase difficulty after you can explain the core answer clearly, not just recognize the solution.'},
    {title: 'Write an answer an interviewer can follow', body: 'Show how you reach the answer and how you would check it.', actions: ['State the conclusion or approach first. Define important assumptions and use the supplied facts.', 'Show the key calculation or steps. For technical roles, discuss edge cases and how you would test your approach; the app does not execute your code.', 'Explain a limitation or alternative, then give the next check. For behavioral answers, describe your own actions and the result without inventing experience.'], example: '“An extra $10 of depreciation lowers net income by $7.50 at a 25% tax rate. Adding back the non-cash expense increases cash by $2.50. I would check that the balance sheet still balances.”', tip: 'A strong answer makes the reasoning easy to challenge. Avoid unsupported certainty and long setup.'},
    {title: 'Check numbers and handle follow-ups', body: 'Use the result fields for the requested numerical outputs and your written answer for the workings.', actions: ['Enter each result with the displayed unit and sign convention. The free check compares that specific number with the expected result.', 'Answer the follow-ups shown by your practice setting. Explain how a changed assumption affects your conclusion.', 'Keep the distinction clear: a matching number does not prove the reasoning is sound.'], example: 'For “change in cash,” enter 2.5 when the expected change is +$2.50. Explain why it is positive in your response.', tip: 'Check units, signs, and rounding before submitting. Most avoidable errors show up in one of those three places.'},
    {title: 'Build evidence with a chart', body: 'Expand Add a visual when a comparison or trend will help explain your answer.', actions: ['Create an exhibit, select bar, line, or area, and give it a meaningful title and axis units.', 'Enter series labels and numeric values or arithmetic. Add or remove series; use View chart data to check the result.', 'Write a takeaway that connects the exhibit to the answer. Download an SVG if you want a separate chart file.'], example: 'Compare a base case and a downside case, then explain which assumption causes the difference.', tip: 'Use consistent units within a chart. Skip the visual when a short explanation is clearer.'},
    {title: 'Review what the app can verify', body: 'Review my answer captures your current attempt and opens the debrief.', actions: ['Read the numerical checks and rework any mismatch. An empty numerical field is not a correct answer.', 'Topic coverage is a signal to inspect your writing, not a mark. Compare your logic with the worked reasoning and next steps.', 'Use View the answer behind this review to check what was assessed. Revise your answer returns to the editor without discarding your work.'], example: '“1 of 1 numerical answers match” means one calculation matches. It does not mean the interview answer earned 100%.', tip: 'Before looking at the reference approach, explain your own answer aloud. It is easier to notice a gap when you have to connect the steps.'},
    {title: 'Get a reasoning grade', body: 'Written-answer grading uses the separate review flow, with criteria for correctness, reasoning, trade-offs, and clarity.', actions: ['Copy grading prompt after submitting, then paste it into ChatGPT yourself. Paste the returned JSON into the review box and choose Import grade & feedback.', 'Read the evidence and suggested improvements for each criterion. Casecraft validates the attempt and score limits and computes the total.', 'Export reviewed scorecard to keep that grade and its feedback. If you revise and submit again, copy a new prompt; the old review belongs to the old attempt.'], example: 'Choose one actionable correction: state the tax assumption, explain the cash-flow add-back, or test the downside case.', tip: 'This is practice feedback, not an employer evaluation. Verify important claims, and do not include private information in a prompt you share.'},
    {title: 'Save, revise, and repeat', body: 'Use each practice to improve one part of how you solve and communicate.', actions: ['Save draft exports JSON; Import restores a file for the same practice. Export debrief keeps the numerical checks and coaching notes. Export reviewed scorecard separately for an imported grade.', 'Drafts and reviews stay in the browser tab. Export important work before closing it; bookmarks and preferences stay on the device.', 'Next practice opens another drill. Continue practice on the catalog resumes your last case. How to practice reopens this guide.'], example: 'Try a short loop: solve unaided → check the calculation → get feedback → revise → explain the improved answer aloud.', tip: 'For a focused first session, allow roughly 15–20 minutes for one core drill and a revision. Adjust for the task; this is a study suggestion, not an interview time limit.'},
  ],
};

export function TutorialIntro({onStart}: {onStart: (path: GuidePath) => void}) {
  return <section className="tutorial-intro" aria-labelledby="tutorial-intro-title">
    <div><span className="eyebrow">NEW TO CASECRAFT?</span><h2 id="tutorial-intro-title">Make your first practice count.</h2><p>Two step-by-step guides, from choosing a case to using your feedback.</p></div>
    <div className="tutorial-paths"><button onClick={() => onStart('competition')}><GraduationCap size={22}/><span><b>Competition Hall guide</b><small>DECA & FBLA · 8 steps</small></span><ArrowRight size={18}/></button><button onClick={() => onStart('career')}><BriefcaseBusiness size={22}/><span><b>Career Launchpad guide</b><small>Interview practice · 8 steps</small></span><ArrowRight size={18}/></button></div>
  </section>;
}

export default function Tutorial({path, onClose}: {path: GuidePath | null; onClose: () => void}) {
  const [step, setStep] = useState(0);
  const title = useRef<HTMLHeadingElement>(null);
  const body = useRef<HTMLDivElement>(null);
  useEffect(() => {setStep(0)}, [path]);
  useEffect(() => {if(path){title.current?.focus({preventScroll:true}); body.current?.scrollTo({top:0});}}, [path, step]);
  if(!path) return null;
  const steps = guides[path], current = steps[step];
  return <Dialog open onOpenChange={open => {if(!open) onClose()}}><DialogContent className="tutorial-dialog">
    <div className="tutorial-heading"><BookOpen size={21}/><div><DialogTitle>{path === 'competition' ? 'Competition Hall' : 'Career Launchpad'} guide</DialogTitle><DialogDescription>Learn the workflow. Close anytime; your practice stays in place.</DialogDescription></div></div>
    <div className="tutorial-progress" aria-label={`Step ${step + 1} of ${steps.length}`}><span>STEP {step + 1} OF {steps.length}</span><progress max={steps.length} value={step + 1}/></div>
    <div className="tutorial-body" ref={body}><nav className="tutorial-contents" aria-label="Tutorial steps">{steps.map((item, i) => <button key={item.title} aria-current={step === i ? 'step' : undefined} onClick={() => setStep(i)}><span>{i + 1}</span>{item.title}</button>)}</nav>
      <article className="tutorial-step"><h2 ref={title} tabIndex={-1}>{current.title}</h2><p className="tutorial-lead">{current.body}</p><ol>{current.actions.map(action => <li key={action}>{action}</li>)}</ol><div className="tutorial-example"><b>For example</b><p>{current.example}</p></div><p className="tutorial-tip"><b>Practice tip</b> {current.tip}</p></article>
    </div>
    <div className="tutorial-navigation"><button className="secondary-button" disabled={step === 0} onClick={() => setStep(n => n - 1)}><ArrowLeft size={16}/> Back</button><button className="text-button" onClick={onClose}>Close guide</button><button className="primary" onClick={() => step === steps.length - 1 ? onClose() : setStep(n => n + 1)}>{step === steps.length - 1 ? <>Ready to practice <Check size={16}/></> : <>Next step <ArrowRight size={16}/></>}</button></div>
  </DialogContent></Dialog>;
}
